### ISSUE TITLE
Crash when notification appears

### ISSUE THREAD

**Issue by fulopm** [minbrowser/min#238] opened 2016-08-15 15:09 UTC
The browser crashes when the WhatsApp webapp (don't know if other sites is affected) pushes a desktop notification. The notification appears, and the browser immediately crashes.

I have ubuntu x64 16.04, and Min 1.4.0-1.

**Comment by PalmerAL** [comment] 2016-08-15 16:25
This happens whenever the Notification API is used.

However, I can only reproduce it in Min - the Electron demo app doesn't crash.

**Comment by MarkWahlsten** [comment] 2016-09-09 06:53
I have also encountered this bug with the Gmail desktop push notifications.

I have OSX Yosemite 10.10.5, and Min 1.4.1

**Comment by PalmerAL** [comment] 2016-09-11 22:07
This appears to only crash sometimes now, which makes it more difficult to reproduce.

Can you try running Min with the latest version of Electron (https://github.com/electron/electron/releases/tag/v1.3.5), and seeing if it still crashes?

**Comment by fulopm** [comment] 2016-11-01 13:58
@PalmerAL, how can I run Min with a specific version of Electron?

**Comment by PalmerAL** [comment] 2016-11-02 04:48
@fulopm You can download Electron from https://github.com/electron/electron/releases, and then run ```/path/to/electron /path/to/min``` (where /path/to/electron is the electron binary, and /path/to/min is a copy of the min repository).

Interestingly, Electron 1.4.5, which was just released yesterday, includes "Fixed a crash when creating notifications on a session that is using a permission request handler", which sounds like it could be what's causing this.

**Comment by Elm7** [comment] 2016-11-22 08:08
Hi, got the same bug with a "segmentation fault" that causes min to close.

**Comment by PalmerAL** [comment] 2016-11-23 00:24
@Elm7 Does this happen when notifications are supposed to appear? It's possible that the crashes you are having could be a different issue.

**Comment by Elm7** [comment] 2016-11-23 10:10
@PalmerAL Hi, this indeed happens when notifications are supposed to appear. I am using debian jessie and latest Min. With Firefox notifications work properly. I do not know how to disable them in Min.

**Comment by PalmerAL** [comment] 2016-12-19 02:01
I think this is fixed in Min 1.5.1; can you try it and make sure?

**Comment by Elm7** [comment] 2016-12-26 16:43
Hello, thanks. Min seems stable now, but I can not make sure because for a reason I dunno notifications are not showing up now even with firefox so I can not test min new vesion stability. I'll come by if I can test it later.

**Comment by PalmerAL** [comment] 2017-11-10 06:28
Going to close this since it appears to have been fixed in Electron; feel free to reopen if you are still having this issue.

**Closed by PalmerAL** 2017-11-10 06:28 UTC
Labels: bug
