### ISSUE TITLE
v1.8.0-beta1 throws JavaScript error on initial startup

### ISSUE THREAD

**Issue by we3geeks** [minbrowser/min#604] opened 2018-09-02 14:00 UTC
OS is macOS 10.11.6

![screen shot 2018-09-02 at 7 57 27 am](https://user-images.githubusercontent.com/2390335/44956750-31411680-ae86-11e8-97aa-2bfdc38871ae.png)

After acknowledging 3 or 4 of those errors, I am presented with the "you've upgraded" page:

![screen shot 2018-09-02 at 8 01 18 am](https://user-images.githubusercontent.com/2390335/44956769-6e0d0d80-ae86-11e8-8a22-414233159a1a.png)

... and when I go to the Min User Survey page, I get something similar:

![screen shot 2018-09-02 at 8 02 21 am](https://user-images.githubusercontent.com/2390335/44956791-a7457d80-ae86-11e8-8f95-e13694989f03.png)

**Comment by PalmerAL** [comment] 2018-09-02 16:55
Sorry about that! I've created a build that shows some additional information in the error message to hopefully make it easier to figure out what's causing this. Could you try running this: https://send.firefox.com/download/d2fe8e5248/#wRCVysk0sQHd13UJddrBTg, and take a screenshot of the error messages you get?

**Comment by we3geeks** [comment] 2018-09-03 12:09
I retrieved the version from the above link, and installed it. It runs without generating any errors (at least so far). And when I've run the v1.8.0-beta1 binary since that initial run, I've not seen that same error. Could this be related to a first run against a v1.7 profile? 

I hate to say it, but I did not set aside a copy of my profile before the first time I ran v1.8.0-beta1. I think I have v1.7 installed on one of my Macs at work. I will try it there as well (after making a copy of my profile).

**Comment by PalmerAL** [comment] 2018-09-03 16:55
I'm not able to reproduce it on an upgraded profile either, so I don't think it's just that. I did actually see this error once a few weeks ago, but I've never seen it again, so it's probably just random. My guess is that there's some kind of race condition when creating new views; Electron seems to normally process IPC messages in the same order that they were sent, but if it didn't, we could end up trying to modify a view before it is actually created.

**Comment by we3geeks** [comment] 2018-09-03 17:16
@PalmerAL: I will do a bit of testing on my other box with a v1.7 profile tomorrow and follow up.

**Comment by we3geeks** [comment] 2018-09-05 03:38
@PalmerAL: I tried this on two other Mac's with Min v1.7.1 installed and could not duplicate it. Your thoughts on random/race condition may be on target...

**Comment by PalmerAL** [comment] 2018-09-07 02:38
I was able to reproduce this again, although it happened when I was closing tabs (which I think is a different scenario than what you were experiencing). In this case, `id` was null, meaning that we're trying to call a method on a view that doesn't exist.

I think what's happening is that we call a method in response to an event, such as here: https://github.com/minbrowser/min/blob/bda68360fa0c13843cbb478776f99b5bc719f15f/js/readerview.js#L124-L128. Because the event is dispatched asynchronously, there's a delay between when the event happens and when we try to call `getURL`. If the view is destroyed during that time, the view won't exist anymore when `getURL` is called, and we'll get an error.

I'm thinking that if the view doesn't exist when we try to call a method, we can probably just ignore the call and not try to execute anything. This seems like it would cause further bugs, but I can't actually think of a scenario where it wouldn't work?

**Comment by code-hunger** [comment] 2018-09-07 04:14
Let's defer that job to the tab itself.

Add a method to the tab's object/module that does this update based on the url. 

 Inside there we can make our decision whether to call asynchronously and what to do in case the tab is closed.

A neat solution is to add the "event listener" (in quotes because it's the callAsync method) to a list in the tab object. On tab destruction, clear the event queue.

What do you think?

**Comment by PalmerAL** [comment] 2018-09-08 02:10
That would work for the `getURL` method, but it wouldn't work for the other async methods (which there aren't many of right now, but there's going to be more eventually), unless I'm not understanding correctly?

After thinking about this more, I think the real issue isn't `callAsync`, but rather the fact that we dispatch events that have happened after the view was already destroyed. I think if we checked [here](https://github.com/minbrowser/min/blob/master/js/webviews.js#L403) whether or not the tab still existed, and just ignored the event if it was already destroyed, that should work?

**Comment by code-hunger** [comment] 2018-09-08 09:27
> we dispatch events that have happened after the view was already destroyed

Where do the events come from if the view is already destroyed?

That file you linked is quite long and with huge functions and I can't really understand what's happening there, but it seems to me that when `ipc.on('view-event',` is fired, there must have been a *view* event coming from a *view*, i.e. a fully existant tab. 
What am I missing here?

**Comment by PalmerAL** [comment] 2018-09-08 15:58
The events come from the main process here: https://github.com/minbrowser/min/blob/master/main/viewManager.js#L6. When an event happens, we send an asynchronous IPC message to the UI process, which is what causes the code in `webviews.js` to run. That code then decides which event handlers to run. The problem (as I understand it) is that in the time it takes for the event to be sent from the main process to the UI process, some code in the UI process could have decided to close the tab. So the view existed when the event actually happened in the main process, but by the time it gets to the UI process, the view doesn't exist anymore. Then, the code in the event listeners tries to call methods of the view, but the view doesn't exist, so we get an error.

**Comment by PalmerAL** [comment] 2018-09-14 23:05
I believe this should be fixed by f9151910331d0241b100ee4fdcb59ff43c662741, but it's possible that there could be more than one cause of this issue. Please open another issue if you see this error happen again!

**Closed** 2018-09-14 23:04 UTC
Labels: bug
