### ISSUE TITLE
Clicking a link will open a blank Tab

### ISSUE THREAD

**Issue by aliencoder16** [minbrowser/min#473] opened 2017-12-22 13:39 UTC
Hi, 
Not sure if this has been mentioned, my search didn't return a similar issue.  If you go to https://news.google.com/news/headlines/section/topic/TECHNOLOGY?ned=us&hl=en&gl=US and try to click a link on it, it will open a blank tab.  If you right click on a link, and tell it to open in a new tab, the page loads fine in a new tab

**Comment by PalmerAL** [comment] 2017-12-22 21:35
I'm guessing this is due to us not supporting window.open fully. My computer's being repaired right now; I'll check for sure when I get it back in a few days.

**Comment by CorbsEditor** [comment] 2017-12-22 21:51
@aliencoder16 Have you tried to scroll clicked on any of the links, that seems to be working for me.

**Comment by aliencoder16** [comment] 2017-12-23 17:47
@CorbsEditor , not sure what you mean by scroll clicking?  If I use right click, open in new tab that works.

**Comment by CorbsEditor** [comment] 2017-12-23 19:54
Yes, right clicking works too. Scroll clicking on a link will open it in a new tab instead of the current tab.

**Comment by PalmerAL** [comment] 2017-12-30 22:42
Yup, Google News uses window.open() to open a new tab when you click on a story for some reason (I'm not entirely sure why, it seems like they could just use a link with target="_blank"). I'm closing this as a duplicate of #140.

**Closed by PalmerAL** 2017-12-30 22:43 UTC
