### ISSUE TITLE
Right mouse click conflict Gmail

### ISSUE THREAD

**Issue by orschiro** [minbrowser/min#276] opened 2016-11-28 07:52 UTC
![image](https://cloud.githubusercontent.com/assets/170947/20660103/f57ad50c-b547-11e6-81b5-502296f9bf25.png)

**Comment by samuel-allan** [comment] 2016-11-28 11:30
Should probably be only the Gmail menu which opens up (firefox does exactly that), I wonder how exactly firefox manages to implement this.

**Comment by PalmerAL** [comment] 2016-11-28 23:34
This is a duplicate of #218.

**Closed** 2016-11-28 23:34 UTC
