### ISSUE TITLE
Feature request: add follow link shortcut (vimperator/vimfx like)

### ISSUE THREAD

**Issue by Tichy** [minbrowser/min#273] opened 2016-11-26 11:25 UTC
Min is a fast and minimalistic browser that's very interesting for those who use tiling window managers in linux. It's almost fully keyboard controllable, but IMHO it lacks the ability to follow links with the keyboard.
In other minimalistic browsers or browser extensions like vimperator, vimfx, vimb, dwm, qutebrowser, you can highlight the links with a keypress and then select which link to follow.

See: https://addons.mozilla.org/en-US/firefox/addon/vimfx/

You can find a javascript that adds this feature for surf browser
http://surf.suckless.org/files/link_hints

**Comment by PalmerAL** [comment] 2016-11-28 23:21
Interesting idea!

I'm not sure enough people would use this to add it to Min. This feature would probably be better as an extension once extension support is implemented (issue #1).

**Comment by Tichy** [comment] 2016-11-29 06:23
On Mon, Nov 28, 2016 at 03:21:51PM -0800, PalmerAL wrote:
> Interesting idea!
> 
> I'm not sure enough people would use this to add it to Min. This feature would probably be better as an extension once extension support is implemented (issue #1).

I think that people could use it if they know it's present. Just think that you
alredy have to keep your hands on the keyboard to go back and forward in
history, that's a function used very often and requires two hands (mod + arrows)
or the right hand which is also used to move the pointer and click links.

Being able to fully navigate with the keyboard would be very useful, as you
don't have to constantly move your hands from the keyboard to the mouse. It
would be make the browser more ergonomic.

-- 
Stefano <cao@cryptolab.net>

**Comment by webavant** [comment] 2017-02-03 05:10
This is a duplicate of #37.

**Comment by PalmerAL** [comment] 2020-08-12 19:13
This has been implemented as a userscript: https://github.com/palmeral/min-vim-mode

**Closed by PalmerAL** 2020-08-12 19:13 UTC
Labels: feature request
