### ISSUE TITLE
wrong link on tabs that errored

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1504] opened 2021-02-14 07:47 UTC
- **Min Version:** 1.18.1
- **Operating system:** Arch

## Expected Behavior
tabs should always have correct url displayed in Task View

## Actual Behavior
![image](https://user-images.githubusercontent.com/22417494/107871374-4e34fd00-6eba-11eb-8f4d-8f720f477fb3.png)

## To Reproduce
disconnect internet, reload, open task view

**Comment by PalmerAL** [comment] 2021-02-15 08:21
I'm not able to reproduce this - I get the page URL as expected. Can you try this?

1. Go to developer > inspect browser > console.
2. Type "__dirname" and press enter
3. Post the result here.

**Comment by shalva97** [comment] 2021-02-16 15:31
I got it. my bad again. 
![image](https://user-images.githubusercontent.com/22417494/108084325-7e80c500-708d-11eb-804a-e7361a627ff4.png)

Sometimes I open Min from /home/shalva/playground/min, which is from git directly and sometimes from /usr/lib/min which is from Arch package. So if the tab is created from git version and then I open it from Arch version it will display the file path...

I guess you can close this because it is a very rare bug, but I would still be happy if you fix....

**Comment by PalmerAL** [comment] 2021-02-17 08:16
Oh that makes sense. Fixing this is probably more difficult than it's worth - to fix this, you need the internal tab URL to be the root page instead of the URL for the error page, but then sometimes you need to actually reference the internal url, so then you need to store both and audit everywhere the URL is used to make sure you're using the right one. So I'm going to close this as wontfix unless you feel strongly about it.

**Closed by PalmerAL** 2021-02-17 08:16 UTC
Labels: bug
