### ISSUE TITLE
gmail talk can't be poppedout from gmail page

### ISSUE THREAD

**Issue by mfarooqi** [minbrowser/min#398] opened 2017-09-15 18:50 UTC
HI, I downloaded Min browser after searching interms of Minimal and Mini browsers. It's nice and tidy. But a few things to update yet.. Tabs' font is too big! and a few more. 

I'm using gmail in Private tab, and needed to open Google Talk as popup, But that doesn't open.

**Comment by PalmerAL** [comment] 2017-09-16 01:44
Min doesn't support popup windows fully, which is probably why this doesn't work. There's another issue for this; #140.

Aslo, how do you open talk as a popup? I have hangouts in the sidebar (it looks like talk has been discontinued: https://gsuiteupdates.googleblog.com/2017/03/updates-in-g-suite-to-streamline-hangouts-and-gmail.html, and I don't see any way to open the widget in a new window.

**Comment by mfarooqi** [comment] 2017-09-16 15:49
yes this may be correct that it has been discontinued.. but we (related to our project) has some history and contacts.. we do discuss on google talk. (this is just an example)
See the following image and click on that NE arrow on chat's title bar.. left of X and right of "_" icon. 

![image](https://user-images.githubusercontent.com/6302459/30513609-97fb4e8e-9b1f-11e7-8af2-953f3b521791.png)

here is how I pop it out as an external window and stay with my tasks .. i'm taking a fullscreen screenshot. 

![image](https://user-images.githubusercontent.com/6302459/30513640-02b70df8-9b20-11e7-974e-6369fa08d786.png)

I hope i could make this understandable.. 
if popups are fully blocked you can make some list for allowed popups by the user. and only those will pop out.

**Comment by PalmerAL** [comment] 2017-09-18 22:12
Right, I'm not saying we shouldn't support Google Talk, I just didn't know it still existed.

The problem isn't that we're intentionally blocking popups, its that we don't support returning a ```window``` object from ```window.open()```, which prevents sites that rely on this from working.

**Comment by mfarooqi** [comment] 2017-09-22 14:55
Please update.. this WAS Google Talk and no this IS Hangout. I'm sorry for using wrong words. ..

**Comment by PalmerAL** [comment] 2017-09-22 21:40
Don't worry about it... it's the same problem either way, #140. My question was completely unrelated to this issue; I was just curious about it.

**Comment by dbfreem** [comment] 2019-08-04 00:57
duplicate of #140

**Closed by dbfreem** 2019-08-04 00:57 UTC
