### ISSUE TITLE
Unable to log in to Bitwarden

### ISSUE THREAD

**Issue by sbstratos79** [minbrowser/min#1557] opened 2021-04-07 19:05 UTC
- **Min Version:**  1.19.0
- **Operating system:**  Windows 10

## Expected Behavior
I should be able to login when I input my Bitwarden master password

## Actual Behavior

The first time setup of Bitwarden remained stuck on Installing after I input the master password. After restarting Min and clicking the key icon next to any password field, a  pop up appears prompting me to log in to Bitwaren. Inputting my details just locks Min into a loop where it keeps asking to enter the master password again and again. I have 2FA enabled for Bitwarden. That may be the likely cause.

## To Reproduce

Install Bitwarden-cli exe and input Bitwarden details.

Already described them above. Here's a screenshot. [https://i.imgur.com/7JMvEag.png](url)

**Comment by PalmerAL** [comment] 2021-04-07 20:56
Yup, this is because we don't support entering a 2FA code: #929. So I'm going to close this as a duplicate of that.

**Closed by PalmerAL** 2021-04-07 20:56 UTC
Labels: bug
