### ISSUE TITLE
Netflix : Missing widevine component

### ISSUE THREAD

**Issue by jaxmatrix** [minbrowser/min#889] opened 2020-01-21 15:47 UTC
Unable to play videos on netflix showing following error 

```
We cannot find all the required components to play Netflix on this device. Please visit chrome://components, locate the WidevineCdm component, and click on the "Check for update" button.

For additional assistance resolving this issue, please visit our Help Centre. https://help.netflix.com/support/27451

Error Code: M7701-1003
```

**Comment by PalmerAL** [comment] 2020-01-21 22:20
Duplicate of #641.

It likely isn't possible for us to fix this, for the reasons explained here: https://blog.samuelmaddock.com/posts/the-end-of-indie-web-browsers/

**Closed by PalmerAL** 2020-01-21 22:20 UTC

**Comment by gpioneer90** [comment] 2021-01-03 23:24
How come forks of Firefox such as Basilisk and Waterfox can have Widevine and other DRM in it? Maybe they have found an easier/free way to include it?

**Comment by Syndamia** [comment] 2021-01-04 08:04
From what I found, [Google's Widevine](https://en.wikipedia.org/wiki/Widevine) is the only way to add DRM support, but as stated in the [Criticism section](https://en.wikipedia.org/wiki/Widevine#Criticism) and [this article](https://boingboing.net/2019/04/03/i-hate-being-right-2.html), Google doesn't want to support opensource browsers, like this one, anymore.

Waterfox, of course, uses Widevine. I'm not 100% certain how they worked out the license, but I believe they're just using Firefox's setup.

**Comment by PalmerAL** [comment] 2021-01-05 00:01
Since I looked into this last, this company has started claiming to offer free widevine licenses through a sub-license with Google: https://github.com/castlabs/electron-releases/wiki/EVS. There's some downsides to this as well (you're dependent on them for Electron updates, and the build process becomes harder), but it looks more feasible than anything else I've seen.
