### ISSUE TITLE
New Window (cmd+n) wipes your currently opened window

### ISSUE THREAD

**Issue by bradymat** [minbrowser/min#255] opened 2016-09-26 07:23 UTC
Love the app, little bug that cmd+n gives you a new window without any trace of your old window existing

**Comment by PalmerAL** [comment] 2016-09-27 03:35
I think this is part of #149. Currently, cmd+n closes all open tabs, while shift+cmd+n creates a new task. This should probably the opposite, since it's harder to accidentally close all of your tabs and (like you mentioned) better matches the "open new window" behavior. The problem is that since shift+cmd+n currently creates a new task, changing the behavior of that to "close all tabs" would be confusing.

I'm not sure what the best way to solve this is. Possibly, this wouldn't be too confusing and the keyboard shortcuts could be reversed in the next release, but I'm not sure if that's a good idea.

**Comment by bradymat** [comment] 2016-09-27 08:44
Thanks heaps for responding, I think switching them would be a good fix. Another completely unrelated thing that has kind of been bugging me is localhost doesn't auto complete to ports. As you start typing it will just go to localhost not localhost:3000 for example if its your last used/most used port. I love the browser, Electron apps are awesome and I'll be using it as much as I can reguardles. Since its so lightweight and has a great minimilistic UI and chrome dev tools which is basically all I need
Great work and support 💯

**Comment by PalmerAL** [comment] 2016-10-01 01:53
@bradymat Can you file a separate issue about autocompleting ports?

**Comment by PalmerAL** [comment] 2016-10-12 22:55
The shortcuts have been switched in 28dfa1fa63fabae79d73148577929899304004dd.

**Comment by PalmerAL** [comment] 2016-10-13 04:04
This has been released in 1.5.

**Closed by PalmerAL** 2016-10-13 04:04 UTC
