### ISSUE TITLE
Copy is broken

### ISSUE THREAD

**Issue by jkanarek** [minbrowser/min#55] opened 2016-04-17 20:21 UTC
Copying via command-c or edit-copy from within a tab doesn't seem to work.

**Comment by PalmerAL** [comment] 2016-04-17 21:19
I can't reproduce this. Which OS are you using?

**Comment by jkanarek** [comment] 2016-04-17 21:21
I'm on a Mac.

**Comment by jkanarek** [comment] 2016-04-18 18:10
I restarted Min and the problem went away, but worth noting that there may be some inconsistency in the copy behavior.

**Comment by dbfreem** [comment] 2019-06-06 02:27
Since this wasn't reproducable and only seemed to happen one time, Closing the issue.

@jkanarek open a new issue if this happens again or repsond here if you are still seeing the issue.

**Closed by dbfreem** 2019-06-06 02:27 UTC
Labels: bug
