### ISSUE TITLE
Tab suspension?

### ISSUE THREAD

**Issue by carsonbird** [minbrowser/min#769] opened 2019-06-11 22:00 UTC
[This](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?hl=en) is a wonderful little plugin.

Is this something that may be worth implementing natively to Min?

**Comment by PalmerAL** [comment] 2019-06-19 02:08
Good idea!

I wonder if this should be part of the tasks changes (#747) - if you collapse a task, we could suspend the tabs in that task until you expand it again.

To do this, we'd probably also have to implement a way of capturing data about the page state (like text typed in inputs) and restoring it; that might be a bit complicated.

**Comment by dbfreem** [comment] 2019-07-15 10:38
This looks like a duplicate of #478 which asked to be able to suspend a task. It didn't mention anything about capturing page state. @PalmerAL I'll let you decide if you want to keep this one open or just keep #478

**Comment by PalmerAL** [comment] 2019-07-16 02:38
@dbfreem #478 is about having a UI to select multiple tabs, I don't think it's directly related. But #355 is a duplicate of this, so I'll close this in favor of that issue.

**Closed by PalmerAL** 2019-07-16 02:38 UTC
Labels: feature request

**Comment by dbfreem** [comment] 2019-07-16 11:52
Your right it was #355 not sure how I got #478. Either way is #355 doable with the current task work or it is too complex?

**Comment by PalmerAL** [comment] 2019-07-16 17:45
It's definitely doable, it's just a question of how much effort to put into it I think. A basic suspending feature would be pretty simple - you would just destroy the BrowserView, and the next time you switch back to the tab, it would be recreated. However, you would also lose any data from that tab - scroll position, the contents of text inputs, etc. If the conditions for when to suspend were pretty strict (e.g. tabs inside collapsed tasks that haven't been opened for a week+), I think that's OK, but if we wanted to suspend more recent tabs or tabs that haven't been collapsed, we'd probably need to implement a way of saving and restoring that data, which could get fairly messy.

I'm probably not going to do anything with this in the current task PR, because I'd like to finish that off before adding more features. I could probably go ahead and do the basic tab suspending after that, but I think I'm going to leave capturing the page state for someone else to do if anyone wants to do it.
