### ISSUE TITLE
No forward button

### ISSUE THREAD

**Issue by BKenzie7** [minbrowser/min#955] opened 2020-04-03 09:41 UTC
There is no reload or forward button on Min. This would help with working on tasks. Also, would it be difficult to get a bookmarks bar enabled? Or at least on the "typing in the new tab page" some sort of section dedicated to bookmarks to make bookmarks worth using?
Also from my real-world observation, Min uses more resources than the new Microsoft Edge. Any way to optimize Min to make it blazing fast? I notice a delay in speed, and it isn't my connection (200mbps) that Edge can load just fine. What can be done to improve the speed of the browser as well as reduce how resource hungry it is?

**Comment by PalmerAL** [comment] 2020-04-04 03:29
Forward button is #744.

I'm not sure I agree regarding a bookmarks bar, but I do think the items on the new tab page could be more useful; I'll probably look into that more at some point.

Is there any particular site or situation where you notice Min being slow? Depending on the site, enabling first-party content blocking in preferences may help.

**Comment by q-codes** [comment] 2020-04-17 03:46
>.....how resource hungry it is?

@BKenzie7  Just out of curiosity, is it 'more hungry' than Firefox, or 'as hungry' as Firefox - what do you think?

**Comment by q-codes** [comment] 2020-04-17 03:49
@BKenzie7 There is a keyboard shortcut for forward, though.....(ctl + right) works fine for me.

**Comment by BKenzie7** [comment] 2020-04-19 22:10
> > .....how resource hungry it is?
> 
> @BKenzie7 Just out of curiosity, is it 'more hungry' than Firefox, or 'as hungry' as Firefox - what do you think?

I feel it is about as hungry as Microsoft Edge (The chromium rewrite), that is the only browser I have tested it against. 

In my experience, Firefox isn't as hungry as Edge, so it might be a bit less, or around the same space as Firefox.

**Comment by Sestowner** [comment] 2020-07-08 17:42
Duplicate of #744.

**Closed by Sestowner** 2020-07-08 17:42 UTC
