### ISSUE TITLE
error open dev tools

### ISSUE THREAD

**Issue by brakdag** [minbrowser/min#488] opened 2018-01-27 13:10 UTC
erro open dev tools in windows.
crash and close app.

**Comment by PalmerAL** [comment] 2018-01-27 17:56
It works fine for me. Does this happen in the electron sample app (https://github.com/electron/electron/releases)?

**Comment by Sestowner** [comment] 2020-07-19 10:04
I can't reproduce this, so I'm going to close this issue. Feel free to reopen this if you have the problem again.

**Closed by Sestowner** 2020-07-19 10:04 UTC
Labels: OS/Windows, bug
