### ISSUE TITLE
MediaFire Issue

### ISSUE THREAD

**Issue by Ema-byte** [minbrowser/min#1446] opened 2021-01-19 07:05 UTC
Hi, I found out that the COOKIES consent/deny pop-up in mediafire.com isn't clickable.

**Comment by Ema-byte** [comment] 2021-01-19 17:55
> Hi, I found out that the COOKIES consent/deny pop-up in mediafire.com isn't clickable.

Experiencing this same issue with the same cookie's popup in other websites.

**Comment by Syndamia** [comment] 2021-01-21 13:02
Duplicate of #1416, which in turn is a duplicate of #1381

**Closed by Syndamia** 2021-01-21 13:02 UTC
