### ISSUE TITLE
"you're using an Older version of Chrome" prompt on visiting google.

### ISSUE THREAD

**Issue by robocopAlpha** [minbrowser/min#514] opened 2018-03-12 07:19 UTC
When I visit google.com then I see a prompt saying **"We've detected you're using an older version of chrome"**. Then a button says **"re-install to stay secure"**.

![screen shot 2018-03-12 at 9 15 13 am](https://user-images.githubusercontent.com/35454738/37270175-779e5ee6-25d6-11e8-8eb3-af2821e0ec0d.png)

I guess it's pretty harmless, but as I don't know what triggers this so I'm reporting it here.

**Comment by PalmerAL** [comment] 2018-03-12 21:39
Duplicate of #485.

**Closed by PalmerAL** 2018-03-12 21:39 UTC
