### ISSUE TITLE
Reload should clear cache

### ISSUE THREAD

**Issue by LouieTian0209** [minbrowser/min#883] opened 2020-01-09 03:48 UTC
I'm in web development industry and right now I'm using both Min and Chrome (as Chrome is the preferred browser for most people so I have to have it handy) and I have run into issues where the administrators have published a new version of the front end but I'm still looking at the old version. This can be resolved on Chrome by right clicking on the refresh button and select "Clear Cache and Hard Reload", so I'm wondering if I can do the same in Min so I don't have to jump back and forth between Chrome and Min while I'm developing stuff. Thank you for your time and I truly enjoy this fantastic project!

**Comment by PalmerAL** [comment] 2020-01-09 23:16
I think the best way to do this right now is to open the devtools, enable network > disable cache, and then reload. It probably makes sense to just make hard reloading the default though.

**Comment by Syndamia** [comment] 2021-06-20 07:33
@PalmerAL isn't this a duplicate of #381?

**Comment by PalmerAL** [comment] 2021-06-20 20:02
Yup, and there's actually a new shortcut for this in the latest release (from #1601).

**Closed by PalmerAL** 2021-06-20 20:02 UTC
Labels: feature request, good first issue
