### ISSUE TITLE
Add support for webcam

### ISSUE THREAD

**Issue by qoobi** [minbrowser/min#110] opened 2016-04-26 20:01 UTC
I couldn't find a way to let a website use my webcam

**Comment by dbfreem** [comment] 2019-07-14 00:34
@PalmerAL is this still a desired feature to add? I understand it's usefulnes but for a minimal browser may be an edge case for now.

**Comment by PalmerAL** [comment] 2019-07-14 03:06
I think so, there's a pretty large number of sites that use this - hangouts, skype, etc. And since this is really an issue with requesting permissions in general, fixing this would also allow for geolocation and other permissions, which a ton of websites use. But I agree figuring out how to integrate this into the UI might be difficult.

This is a duplicate of #332 though.

**Closed by PalmerAL** 2019-07-14 03:06 UTC
Labels: enhancement
