### ISSUE TITLE
window.opener.postMessage error

### ISSUE THREAD

**Issue by igk1972** [minbrowser/min#446] opened 2017-11-05 11:32 UTC
Site netlify.com (and many others) do authentication after logging in in the new window and refreshing the main window.

Problem:
window.opener is nuil.

See
- https://github.com/electron/electron/issues/9533
- https://github.com/electron/electron/pull/9961
- https://github.com/jiahaog/nativefier/issues/164

![2017-11-05 14 21 49](https://user-images.githubusercontent.com/54089/32414373-1bca9e80-c236-11e7-861c-2c91495f8106.png)

**Comment by PalmerAL** [comment] 2017-11-05 16:24
Duplicate of #140.

**Closed by PalmerAL** 2017-11-05 16:24 UTC
