### ISSUE TITLE
Cannot reload on Github.com

### ISSUE THREAD

**Issue by z3t0** [minbrowser/min#340] opened 2017-04-12 15:43 UTC
Github seems to have a mapping for "r" so command-r doesnt reload

**Comment by PalmerAL** [comment] 2017-04-16 16:18
I can't reproduce this - pressing command+R seems to reload the page.

If you have scrolled to the top of the page, there probably isn't any visible result of reloading, since the old page is replaced by the new page without any flickering. If you scroll down, do you see the page move back to the top when you reload it?

**Comment by code-hunger** [comment] 2017-05-05 18:49
I can't reproduce it, too. Either way, if github's mapping is for `r`, then it will not mess up since `ctrl-r` is caught and processed at a much lower level.

**Comment by PalmerAL** [comment] 2019-07-29 22:15
I still can't reproduce this, so I'm going to close this issue; let me know if you notice this again and I'll re-open it.

**Closed by PalmerAL** 2019-07-29 22:15 UTC
