### ISSUE TITLE
Could you please add vim-like mode keybindings

### ISSUE THREAD

**Issue by palagend** [minbrowser/min#660] opened 2018-11-05 06:23 UTC
Hi:
The lightweightness of the min browser is attractive, but I cannot get the same mouse-free experience when using min browser as using Chrome Browser with vimium plugin. Could you please add vim-like mode keybindings in min browser?
Thanks!

**Comment by PalmerAL** [comment] 2018-11-07 08:36
Duplicate of #37. 

If you go to the settings page, you can modify the keyboard shortcuts to be single characters, which allows you to replicate a lot of the shortuts in the vimium extension. That being said, we don't support every shortcut vimium does - are there specific ones you would particularly like to see added?

**Closed by PalmerAL** 2018-11-07 08:36 UTC
