### ISSUE TITLE
Error Installing Min in Ubuntu 14.04

### ISSUE THREAD

**Issue by tradesmanhelix** [minbrowser/min#14] opened 2016-04-13 14:22 UTC
When installing the .deb package from the Min website, Ubuntu 14.04 gives the following error:

```
The package is of bad quality

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organization which provided this package file and include the details beneath.

Lintian check results for /home/user/Downloads/Min_1.1.1_amd64.deb:
E: Min: package-has-no-description
E: Min: bad-package-name
E: Min: package-not-lowercase
E: Min: wrong-file-owner-uid-or-gid usr/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/bin/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/bin/Min 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/LICENSE 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/LICENSES.chromium.html 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/Min 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/content_shell.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/icudtl.dat 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/libffmpeg.so 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/libnode.so 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/am.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ar.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/bg.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/bn.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ca.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/cs.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/da.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/de.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/el.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/en-GB.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/en-US.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/es-419.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/es.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/et.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/fa.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/fake-bidi.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/fi.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/fil.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/fr.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/gu.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/he.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/hi.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/hr.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/hu.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/id.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/it.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ja.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/kn.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ko.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/lt.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/lv.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ml.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/mr.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ms.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/nb.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/nl.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/pl.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/pt-BR.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/pt-PT.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ro.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ru.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/sk.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/sl.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/sr.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/sv.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/sw.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/ta.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/te.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/th.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/tr.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/uk.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/vi.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/zh-CN.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/locales/zh-TW.pak 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/natives_blob.bin 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/.DS_Store 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/.gitignore 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/Gruntfile.js 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/README.md 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/css/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/css/base.css 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/css/findinpage.css 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/css/navbarTabs.css 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/css/searchbar.css 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/css/webviews.css 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/dist/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/dist/.DS_Store 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/dist/build.js 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/dist/build.min.js 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/dist/webview.js 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/dist/webview.min.js 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/ext/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/ext/.DS_Store 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/ext/Dexie.min.js 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/ext/abp-filter-parser-modified/ 501/20
E: Min: wrong-file-owner-uid-or-gid usr/share/Min/resources/app/ext/abp-filter-parser-modified/.DS_Store 501/20

...and so forth...
```

System info:

```
User: user
Hostname: ubuntu
OS: Ubuntu 14.04 x86_64
Kernel: 3.13.0-85-generic
Uptime: 1:40
Window Manager: Compiz
Desktop Environment: GNOME
Shell: Bash
Terminal: Xterm
Packages: 2070
CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
RAM: 2480 MB / 3950 MB
Disk: 12G / 62G
```

**Comment by chalda** [comment] 2016-04-13 17:07
came here to post this. Running into the same problems. OS X isnt the only operating system out there :\

**Comment by tradesmanhelix** [comment] 2016-04-13 17:34
*sigh of relief* Glad to know that I'm not the only one who ran into this issue! There **is** an "install anyway" button...wonder if anyone has been brave enough to attempt that... 😬

**Comment by chalda** [comment] 2016-04-13 18:27
I donno, too many errors for me to blindly trust an installer. Rather not
accidentally bork my os. Considering its a grunt/node project, installing
from source is probably pretty easy .

**Comment by forteller** [comment] 2016-04-16 19:24
I have the exact same issue on Ubuntu Gnome 15.10 64 bit with Gnome 3.18. Was looking forward to try this, but a million error messages means I wait :)

**Comment by MustafaHaddara** [comment] 2016-04-19 13:35
Ran into the same problem here as well, I'm on elementary freya 0.3.2 (for all intents and purposes: Ubuntu 14.04)

**Comment by mbarakaja** [comment] 2016-04-21 07:02
Same issue here

**OS:** `Ubuntu 10.15 64-bits`

**Comment by asimilon** [comment] 2016-06-02 09:21
Still same issue with min_1.3.1_amd64.deb package on ubuntu 14.04LTS 64-bit, seems no-one cares.

Some system info if it's useful : 
Processor : Intel® Core™ i7-3720QM CPU @ 2.60GHz × 8 
Graphics : NVS 5200M/PCIe/SSE2
Memory : 15.6 GiB
Disk : 240gb SSD

**Comment by netsgnut** [comment] 2016-11-23 05:37
Would like to report that the above issue is still observed with min_1.5.0 on Elementary Freya (Ubuntu 14.04/Trusty).

**Comment by netsgnut** [comment] 2016-11-23 05:41
Related issue: unindented/electron-installer-debian#16

**Comment by PalmerAL** [comment] 2016-11-24 02:10
Unfortunately, I don't have any ideas about how to fix this. For now, I think you can just ignore the warning, since the incorrect permissions don't seem to cause any problems.

**Comment by netsgnut** [comment] 2016-11-25 09:35
From what I understand here all the files referenced in the deb packages should be root, or otherwise it would prompt the error. In case if anyone is working on it, followed is an output of the `lintian` for errors/warnings for the package.

I have yet tried running the packaging script on a Mac yet. In case anyone of us is reading this, [probably how Atom packages their `.deb` files can be a reference](https://github.com/atom/atom/blob/master/script/lib/create-debian-package.js), although it seems to be similar to [what `electron-installer-debian` is doing](https://github.com/unindented/electron-installer-debian/blob/master/src/installer.js).

**Comment by dbfreem** [comment] 2019-02-12 03:07
@PalmerAL  should this still be left open. I was able to install on Ubuntu 18.04 without any issues.

**Comment by PalmerAL** [comment] 2019-02-12 23:10
I can't reproduce this anymore either, I think it's fine to close it.

If anyone else is still having this problem, please let me know and I'll reopen it.

**Closed by PalmerAL** 2019-02-12 23:10 UTC
Labels: Linux, help wanted
