### ISSUE TITLE
Content blocking issue on https://www.youtube.com/watch?v=JpY6P9eJ6u0

### ISSUE THREAD

**Issue by OliverRozario** [minbrowser/min#1888] opened 2022-01-25 17:32 UTC
Min does not remove ads

**Comment by Kepler-69c** [comment] 2024-02-03 19:39
(duplicate of https://github.com/minbrowser/min/issues/1121)

Min's built-in adblocker currently doesn't work reliably on YouTube. To block ads on youtube, you can try https://github.com/minbrowser/min/issues/1121#issuecomment-663021909 or [this one](https://github.com/alisanoelia/yt-block) instead.

How to use user scripts is explained on the [Min GitHub wiki](https://github.com/minbrowser/min/wiki/userscripts).

Feel free to ask if you still have problems!

**Closed by Kepler-69c** 2024-02-03 19:39 UTC
Labels: status/duplicate, bug/content-blocking
