### ISSUE TITLE
microphone

### ISSUE THREAD

**Issue by JeanRD2** [minbrowser/min#2228] opened 2023-04-24 18:55 UTC
why this browser dont let me use the microphone and camera?

**Comment by Oleksandr0118** [comment] 2023-04-28 07:55
The same problem, the microphone and camera do not work in the newest version, download the previous version 1.26.0

**Comment by anhood** [comment] 2024-01-27 17:11
See ticket # 1874
https://github.com/minbrowser/min/issues/1874

**Comment by Kepler-69c** [comment] 2024-04-27 19:35
closed as a duplicate of #1874

**Closed by Kepler-69c** 2024-04-27 19:35 UTC
Labels: bug, status/duplicate
