### ISSUE TITLE
auto dark mode for web contents in Min

### ISSUE THREAD

**Issue by ahmeteid7** [minbrowser/min#2412] opened 2024-03-27 13:41 UTC
there is flag in chrome it's name auto dark mode for web contents(enable with simple cielab-based invertion), i ask if i can use it in Min-browser, can i get the souce code of that flag and use it as userscript in Min?

**Comment by PalmerAL** [comment] 2024-03-28 19:23
Duplicate of https://github.com/minbrowser/min/discussions/2386.

It's not directly possible to enable a flag through a userscript, but it might be possible by modifying the Min code.

Also, you could try this: https://github.com/PalmerAL/min-dark-mode-userscript

**Closed by PalmerAL** 2024-03-28 19:23 UTC

**Comment by ahmeteid7** [comment] 2024-03-28 19:52
> Also, you could try this: https://github.com/PalmerAL/min-dark-mode-userscript

i tried that, but it's not good, it converts the sites that has default dark theme style to light
