### ISSUE TITLE
Can't minimize window in some linux distros

### ISSUE THREAD

**Issue by lee-yunseok** [minbrowser/min#1074] opened 2020-06-18 14:47 UTC
As a sub, I found a problem in video streaming. Min can't minimize window when streaming video on youtube and vimeo. It probably the same on other streaming platforms.

I'm not sure if this problem that only occurs in RPi.

**Comment by PalmerAL** [comment] 2020-06-18 16:35
Is the video in fullscreen? Is the issue that there isn't a minimize button, or that clicking on it doesn't work? Do the other window buttons (close, maximize) still work?

**Comment by lee-yunseok** [comment] 2020-06-18 16:45
Video in frame. Other buttons work fine.

More exactly, when I click the minimize button, it work but restored immediately.

**Comment by lee-yunseok** [comment] 2020-06-19 07:26
Still having the issue.

**Comment by PalmerAL** [comment] 2020-06-22 22:06
I can't reproduce on Ubuntu, so it may be specific to RPI-OS. I have a Pi I could test this on, but it may be a while before I get around to setting it up again.

Does it work if you enable the "use separate titlebar" option? Also, was this working in a previous version?

**Comment by lee-yunseok** [comment] 2020-06-23 07:21
Yes it work with enable separate titlebar. I don't remember when this feature was added but minimize worked before.

**Comment by lee-yunseok** [comment] 2020-06-25 21:10
Re-install also doesn't work. So enable separate titlebar may be needed for pi users.

**Comment by shalva97** [comment] 2020-07-02 19:12
I have same issue on Arch Linux KDE

**Comment by Emmanuel65** [comment] 2020-07-05 07:39
Hi! The same on Lubuntu 18.04.4 64 bitafter the latest ugrade.

**Comment by Sestowner** [comment] 2020-07-06 13:55
I'm facing the same issue when I disable the "Use separate title bar" option.
**OS**: Linux Mint 19.3
**Min**: 1.15.0

Looks like this issue derived from 38c9ff4ac4adf3db18b213b30a4ad8f3fdf502b5.

**Comment by shalva97** [comment] 2020-07-06 15:45
I think this is also related to this...

if browser is maximized, pressing CTRL + R twice to reload browser i get few pixel margins at the top of the browser. Remaximizing the window fixes this

**Comment by PalmerAL** [comment] 2020-07-08 21:29
@Sestowner Thanks for finding that. I don't see right now how that could cause this  problem, but I guess we can back it out if we don't find a solution.

I've tried this in:
* Stock Ubuntu
* Ubuntu with vanilla GNOME
* Ubuntu running LXQt

and I can't reproduce it in any of them, so there must be some other factor. Are there any other factors that you can think of in your environment that could cause this?

@shalva97 That's an unrelated issue; the drag space gets hidden when you maximize the window, but it loses the state when reloaded.

**Comment by Sestowner** [comment] 2020-07-09 20:47
I just checked this on Cinnamon (before I used Openbox), and I didn't encounter this issue.

**Comment by PalmerAL** [comment] 2020-07-09 22:11
I was able to reproduce this once on Openbox, but after restarting Min, I no longer see it.

**Comment by Sestowner** [comment] 2020-07-10 11:34
BTW, I can minimize Min on Openbox when the address bar is active or when the task overlay opened.

**Comment by PalmerAL** [comment] 2020-07-10 19:47
Thanks, I can reproduce it now. (And that would make sense, because `webviews.placeholderRequests.length === 0` will be false in those cases).

**Comment by PalmerAL** [comment] 2020-07-10 20:12
This is strange:

* If you have a button inside a frameless window that calls `minimize` when clicked, then it actually triggers a `focus` event on the window as it minimizes.
  * If you make the window not frameless (which is what "use separate titlebar" does), it doesn't happen.
  * If you get rid of the button (and call minimize() from `setTimeout`), it doesn't happen.
* Due to the change above, when the `focus` event happens on the window, the BrowserView will be focused (which is what should happen, in theory).
* Focusing the BrowserView un-minimizes the window (which also doesn't make much sense).

The only thing I can think of at the moment is whenever we get a `focus` event, to check if we called `minimize` shortly before that, and ignore the `focus` event if we did. But that seems like it's not a very good solution.

**Comment by PalmerAL** [comment] 2020-07-23 19:48
@Sestowner I've added a workaround for this in 99d94d06874253da1ff66bfe79f00ad2727b103d; can you test it and make sure that the window now minimizes correctly, and that the page still gets focused again when you re-focus the window?

**Comment by Sestowner** [comment] 2020-07-24 07:36
@PalmerAL I tested your workaround and it works great for me.

**Comment by PalmerAL** [comment] 2020-07-25 20:56
@Sestowner Thanks!

I'm going to close this since I think it's fixed, but if anyone else still has this issue after the next update, please let me know.

**Closed by PalmerAL** 2020-07-25 20:56 UTC
Labels: OS/Linux, bug
