### ISSUE TITLE
multiple windows

### ISSUE THREAD

**Issue by kowal05** [minbrowser/min#996] opened 2020-05-02 09:40 UTC
i have been using min as my amin webrowser for a month now and i really like it, but i find it a little bit iritating that you can have more that one windows of min at the same time.(a least on windows)

sorry for grammar english is not my first lanuage

**Comment by PalmerAL** [comment] 2020-05-02 21:57
Duplicate of #169.

**Closed by PalmerAL** 2020-05-02 21:57 UTC
