### ISSUE TITLE
Add Change Start Page in Min

### ISSUE THREAD

**Issue by anim4k** [minbrowser/min#542] opened 2018-04-10 12:43 UTC
hey i try this browser gnu/linux is very wonderful fast and speed <3 
I have a suggestion about adding a start page is important!
Sometimes I go through my work and I find my colleagues automatically watching what I was watching and this is bad
https://i.imgur.com/NJjSHLd.png

**Comment by PalmerAL** [comment] 2018-04-10 22:26
Duplicate of #211.

**Closed by PalmerAL** 2018-04-10 22:26 UTC
