### ISSUE TITLE
we should use Github Projects

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1262] opened 2020-09-30 12:17 UTC
**Can you describe the problem you're facing?**
@PalmerAL you seem to be randomly solving issues and i cant find a way to know whats going to be added next to Min. maybe some people want to know what is being added to min or comment some ideas. and i am one of them...

**What solution would you like?**
we should have [Github Projects]( https://github.com/features/project-management/)  so everyone would see exactly what is happening. 
For example the Dart language has [Language Funnel](https://github.com/dart-lang/language/projects/1) where they put all of the issues to discuss and then they implement it. So what do you think @PalmerAL ? 

**Are there any alternatives you've considered?**
ummm, maybe Jira?

**Comment by PalmerAL** [comment] 2020-10-02 05:42
Yeah, this seems like a good idea; I'll try to start organizing some specific issues at some point.

Part of the issue is that I don't have a really specific plan; I tend to get ideas as I use Min and work on those, and also my schedule is fairly unpredictable, so it's hard to plan things in advance. But just to give an idea of some of what I'm planning to work on:

near-term goals:
* Improve password management in Min by:
  * Making the 1password integration less buggy
  * Adding a way to save passwords using the system keychain storage (so you could save passwords directly in Min without connecting an external manager).
* Continue to fix bugs

Medium-term goals:

* Work on making the bookmark manager more intuitive to use, and making it easier to access bookmarks
* Improving the quality of the searchbar results (particularly full-text results).
* I've also been thinking a lot about how to integrate a note-taking system/text editor that would make it easy to combine your writing with snippets of content from webpages. I don't have a really concrete plan for this yet though, so I don't have any idea whether I'll actually end up doing anything with this or not.

This can obviously change a lot though based on what issues get filed, and what you or other people suggest, so I wouldn't take this as a completely fixed list.

**Comment by shalva97** [comment] 2020-10-07 19:30
> I don't have a really specific plan

well, there could be tasks, at least general tasks, like "next few weeks i will improve X, Y, Z features"  and people could come and discuss some ideas.

for example there could be a task in Github Projects "Making the 1password integration less buggy"

i would definitely comment this: 

> Never used password managers before, mostly because im paranoid and dont trust them. few days ago i tried and oh god it is so bad. It works but the way it asks to configure it is incredibly suspicious.
> - you are literally asking users to download an executable file and drag it in a popup. But why? i cant even see the link from where it downloads. This reminds me of myself 5 years ago when i was browsing random torrent site clones, where they would ask you to "hey click this random executable file,which is not a virus, and enjoy your movie".
> - the popup has "not now" button. okay, this is fine, but the user should have control when it is the time. that popup should not show up every single minute. but the worst part is that it even requests browser focus. why? this gave me exact feeling i would get  5 years ago when i would download that freebitcoin.exe and random adds  would open every minute and interrupting me. 
> - i get it, for the password autofill to work 1password-cli is needed. but please not like this, i may trust Min browser, because i can read source code and see what is going on(okay im lazy, havenot read most of it :d) but later you shouldnot ask to download weird closed source executable.
> - if i drag&drop how would you handle its updates? please dont tell me that same popup would show up, steal focus and ask for another executable to be downloaded and drag&dropped.
> - if you dont link the docs of `op` file. how would i figure out that you are actually using 1password-cli and i have to login by `op signin example.1password.com wendy_appleseed@example.com`. I may be wrong here? i didnot drag&drop that file, but downloaded it from [here](https://aur.archlinux.org/packages/1password-cli/).
> - instead, there should be instructions, "hey go to this official page and install it  from [there](https://1password.com/downloads/command-line/) and this is the [doc](https://support.1password.com/command-line-getting-started/)".
>
> well at least it worked.
> i mean bottom line is to **not** show recurring popups asking executable file downloads, like a torrent website where they promise you can watch a movie if you take their free bitcoins. 
> also it is interesting what led you to a thought like "okay, this password manager implementation is okay to be included in min"?
> btw, that popup is perfect for this [issue](https://github.com/minbrowser/min/issues/1247)

Medium-term goals seem okay, except 

> note-taking system/text editor

is that really needed? there are plenty of other websites offering note taking functionality. for example Evernote, which i use it only when i need some information to be on my phone and on PC. whithout sync it will be less useful....

**Comment by PalmerAL** [comment] 2020-10-08 20:04
Yeah I agree some level organization would be good even if it isn't perfect.

In regards to the password manager:

> the popup has "not now" button. okay, this is fine, but the user should have control when it is the time. that popup should not show up every single minute. but the worst part is that it even requests browser focus. why? this gave me exact feeling i would get 5 years ago when i would download that freebitcoin.exe and random adds would open every minute and interrupting me.

The intent is that the popup appears immediately after you enable the password manager in the settings; the only way that wouldn't happen is if you choose "not now", in which case it should appear immediately on the next launch. You should never see the popup randomly while browsing - if you are, can you file a bug for it?

> i get it, for the password autofill to work 1password-cli is needed. but please not like this, i may trust Min browser, because i can read source code and see what is going on(okay im lazy, havenot read most of it :d) but later you shouldnot ask to download weird closed source executable.

The executable is produced by the same people as the password manager itself; if you're using this feature, then you've already installed the main password manager binary and are keeping your passwords in it, so I don't see how the CLI would add any additional concerns.

I don't think we actually have a way of handling updates at the moment (we probably should). But I do agree stealing focus is bad; that would probably need to be some kind of background notification you opt-in to.

> if you dont link the docs of op file. how would i figure out that you are actually using 1password-cli and i have to login by op signin example.1password.com wendy_appleseed@example.com. I may be wrong here? i didnot drag&drop that file, but downloaded it from here.

Once you drop the executable file, you'll be prompted to login, but I suppose it's true that that doesn't really work if you're installing a package.

> instead, there should be instructions, "hey go to this official page and install it from there and this is the doc".

Yeah, that's a good point, and I agree we should add a link to that. But a significant portion of our users don't know how to use the command line, so there needs to be an alternative that's easier to use.

**Comment by Milad-Laly** [comment] 2020-10-10 00:41
To organise ideas would it not be better to use a kanban board and organise what features are needed? Like in my fulltime job we use ZenHub and it makes it so much easier to see what things are being worked on and what is needed? Also, I could suggest weekly standups/scrum meetings so we know what people are doing. Agile methodology has helped my team so much in making sure everything is implemented for the release dates.

**Comment by Syndamia** [comment] 2020-10-10 07:55
> To organise ideas would it not be better to use a kanban board and organise what features are needed?

GitHub projects implements the kanban methodology.

![image](https://user-images.githubusercontent.com/46843671/95649308-9182f780-0ae5-11eb-89a5-9e251885ac3d.png)
*Example picture I found ; this is what a GitHub project looks like*

> Also, I could suggest weekly standups/scrum meetings so we know what people are doing.

Agile is a must for companies and such, but this is a public project. Everyone works on this whenever and however they can, so meetings won't really work out how they would in a company. Also, from what I've seen most collaborators (including me) help with issues from time to time, PalmerAL is practically the only one who writes code.

> Also, would it not be ideal to have checks for the PR's to make sure anything added isn't breaking the master branch?

I mean, I think everything is ran and discussed before merge, so nothing in master should (at least majorly) break.

**Comment by Milad-Laly** [comment] 2020-10-10 12:55
Correct me if I'm wrong @Syndamia but Electron is using JS to use the framework and I have experience with JS and Electron doesn't seem too different then normal Node.JS/JavaScript. I can easily get familar with Electron because of my main role. IDM coding but I prefer to know what features are needed. I do genuinely think we need GitHub Project or something that is cheaper. 

> Everyone works on this whenever and however they can, so meetings won't really work out how they would in a company. 

At my full time job, we have projects similar to Min where people work whenever they can alongside their main role. For example, we have weekly scrums on what we are doing and we work at the most random times like I work on those projects when Travis is building or I'm waiting for a slack message from someone else. Obviously right now it isn't needed as only PalmerAL is coding. 

> I think everything is ran and discussed before merge, so nothing in master should (at least majorly) break

I know but it is good code practice, I've ran things that worked on my mac but didn't work on the actual travis build. It failed and I wouldn't have caught onto it and it would have broke the master repo.

**Comment by Syndamia** [comment] 2020-10-10 13:36
> I can easily get familar with Electron because of my main role.

Awesome, I was talking about how things are right now, I didn't know you had experience in JS.

> Obviously right now it isn't needed as only PalmerAL is coding.

Yeah, ok, I agree. If we get more people to code for the project agile might actually be a good idea.

> I know but it is good code practice

Yeah, agreed. 

> Do you know if Github Project costs anything?

GitHub projects is completely free, it's as free as issues.

**Comment by Milad-Laly** [comment] 2020-10-10 13:45
> Awesome, I was talking about how things are right now, I didn't know you had experience in JS.

I have experience in a lot of stuff tbh. Like I'm super comfortable with Python and C++. With JavaScript and Java I'm decent but I wouldn't say I'm a total pro. I can hold my weight if that makes sense? 

Perfect bro, obviously it might not be a priority right now but we can look into it. 

> GitHub projects is completely free, it's as free as issues.
Oh really? I thought it cost like ZenHub. I don't have permissions to create a project so if you do @Syndamia do create one and we can start organising.

**Comment by Syndamia** [comment] 2020-10-10 13:47
> I don't have permissions to create a project 

Only a project owner can, if I'm not mistaken. In any case, only PalmerAL has the permission.

**Comment by Milad-Laly** [comment] 2020-10-10 13:51
Ah okay whenever you are free @PalmerAL can you create a GitHub project and we can take it from there and organise.

**Comment by PalmerAL** [comment] 2020-10-10 19:39
I created a project; let me know if you're not able to edit it.

I do think it's important to find the right balance between planning and actually getting stuff done; it's easy to fall into the trap of having a really detailed plan and not having time to do it (and this is something I run into already - I have a huge pile of unread notifications, but if I take the time to respond to them all, I don't have time to actually do anything).

So what I would suggest is:
* Have a rough outline on a board of what the goals are.
* Meet about them as needed.
* See how much time everyone has to work on solving those issues, and go from there.

**Comment by Milad-Laly** [comment] 2020-10-10 22:01
@PalmerAL i think you would need give permissions to me and @Syndamia to add things into projects. I've never used projects so I'm not sure what permissions are needed.

**Comment by PalmerAL** [comment] 2020-10-10 22:15
I created an organization project board instead: https://github.com/orgs/minbrowser/projects/1 and linked that to the collaborators team. Hopefully that will work; Github's permission model is very confusing.

**Comment by Milad-Laly** [comment] 2020-10-10 22:23
Perfect it works I'll be closing the issue as we are now using Github projects

**Closed by Milad-Laly** 2020-10-10 22:23 UTC
Labels: feature request

**Comment by shalva97** [comment] 2020-10-11 19:34
@PalmerAL it works by the url you provided but not from Min's repo...

**Comment by PalmerAL** [comment] 2020-10-12 02:24
@shalva97 It's an organization board; you have to access it from here: https://github.com/minbrowser
