### ISSUE TITLE
Tab bar doesn't change color on any site

### ISSUE THREAD

**Issue by finnwiley** [minbrowser/min#231] opened 2016-08-08 05:42 UTC
**EDIT: Issue seems to have gone away**
No matter which site I visit, the tab bar turns black rather than the color of the website.
OS: Fedora 24 (Converted .deb to .rpm using alien tool- please let me know if there's a different recommended way to install Min on Fedora)
![screenshot from 2016-08-08 01-33-01](https://cloud.githubusercontent.com/assets/20547068/17470336/605296ae-5d09-11e6-81c8-b4fd8ef239e8.png)
![screenshot from 2016-08-08 01-33-29](https://cloud.githubusercontent.com/assets/20547068/17470214/8b18e0ba-5d08-11e6-9262-cf2279942e25.png)

**Comment by PalmerAL** [comment] 2019-07-29 21:53
I can't reproduce this, so I'm going to close this issue; feel free to open a new issue if you have this problem again!

**Closed by PalmerAL** 2019-07-29 21:53 UTC
