### ISSUE TITLE
Content blocking issue on https://accounts.google.com/accountchooser/deniedsigninrejected?checkedDomains=youtube&continue=https%3A%2F%2Fwww.google.com%2F&dsh=S-1039256138%3A1682622100785989&flowEntry=AccountChooser&flowName=GlifWebSignIn&hl=en&pstMsg=1

### ISSUE THREAD

**Issue by sanjaystorage1** [minbrowser/min#2231] opened 2023-04-27 19:04 UTC
Not able to login to google accounts It says "Not supported device " when I am using "block all trackers and Ad Feature"

**Comment by Kepler-69c** [comment] 2024-02-03 19:25
Duplicate of (#868)

The problem of not being able to sign in to Google is a well-known one (see #868, #863) and has little to do with content blocking. There is still no solution that always works, but you can try 
- enabling user scripts (Preferences -> Enable user scripts)
- changing your user agent (Preferences -> Use a custom user agent) 
- deleting cookies for google.com (right click -> inspect -> application -> delete cookies)

**Closed by Kepler-69c** 2024-02-03 19:25 UTC
Labels: bug, status/duplicate
