### ISSUE TITLE
Windows 10 window not maximized extra space in titlebar

### ISSUE THREAD

**Issue by kontofikcyjne** [minbrowser/min#1024] opened 2020-05-23 22:07 UTC
Hi All,

On Windows 10 there is extra empty space added to the title bar when not maximized comparing to maximized window. Can this extra space be removed? Or maybe add an option to resize the tab/titlebar?

**Comment by PalmerAL** [comment] 2020-05-23 23:15
It's there so that you can drag the window around, because it's not possible to make the tab bar draggable while still allowing you to click on tabs. I suggested moving it to the left corner a while ago (#630), but there are downsides to doing that as well, so I think it's better to leave it as-is.

**Comment by kontofikcyjne** [comment] 2020-05-24 10:34
We can enter drag mode by pressing Alt+SPACE and then click Move option from menu. What about solution similar like in Firefox (2 placeholders to drag window)?

Maybe indeed I'm asking for too much but I think having this as configurable option would be nice for many Windows users.

**Comment by kontofikcyjne** [comment] 2020-05-24 20:25
I figured out how to change this extra space in the code. If anyone is interested then go and change in file min\css\windowControls.css section from line 12 to something like following:

`body.windows:not(.maximized):not(.fullscreen),`
`body.linux:not(.maximized):not(.fullscreen):not(.separate-titlebar) {`
`	/*--control-space-top: 12px;*/`
`	--control-space-left: 20px;`
`}`

The idea was to make drag area in the left corner of the bar but `--control-space-left: 20px;` is not really necessary. I also noticed that it is possible to drag window but clicking & holding area just above tasks button (button with 3 lines). For me this is sufficient workaround but still it would be nice to have that as an option. 

[![min-browser.png](https://i.postimg.cc/bYMDBXJ2/min-browser.png)](https://postimg.cc/hhLtX5VS)

**Comment by PalmerAL** [comment] 2020-05-24 20:42
The actual drag area is controlled by the rule right below that for `.window-drag-area`.

I don't think it makes sense to have this as a built-in option for now, but if we get more feedback on this we can reconsider it.

**Comment by idAlencar** [comment] 2020-05-26 11:04
I think that reducing` .window-drag-area `to `-control-space-top: 6px`; half of the current and still functional, think that placing a location next to a button in the navigation bar just to get rid of it is strange, because it could be a location used to place a button with some action.

Google translator...

**Comment by PalmerAL** [comment] 2020-05-26 19:27
Even the current drag area seems kind of short to me, and when it was 10px tall in the past, there were complaints about it being hard to drag the window, so I'm not sure making it even shorter than that would be a good idea.

**Comment by idAlencar** [comment] 2020-05-26 20:55
complicated @PalmerAL  kkkkkkk, what do you think about adding the option in the settings (set the size of the drag area (4px, 6px, 12px, 16px)?

**Comment by Syndamia** [comment] 2020-08-27 07:35
Closing, because this is very much a duplicate of #630.

**Closed by Syndamia** 2020-08-27 07:35 UTC
Labels: OS/Windows, feature request, status/duplicate
