### ISSUE TITLE
Feedly.com authentication with Google bug

### ISSUE THREAD

**Issue by umountin** [minbrowser/min#272] opened 2016-11-14 07:49 UTC
I'm trying to authenticate to feedly via Google. After I've chose my Google account I've got a message "Login successful This popup should automatically close. If not, please go to http://feedly.com". Then I have gone to feedly.com but authentication had not done. In other browsers I do not have such problem. I do not block any images, scripts and ads in preferences of the browser. I have the last version of the browser (min_1.5.0_amd64.deb).

**Comment by PalmerAL** [comment] 2016-11-16 23:34
I think this is the same as #240. Min doesn't support popup windows fully, so the Google login doesn't work.

**Comment by dbfreem** [comment] 2019-08-04 01:04
duplicate of #140

**Closed by dbfreem** 2019-08-04 01:04 UTC
