### ISSUE TITLE
Linux: looses preferences settings...

### ISSUE THREAD

**Issue by baldrick-nz** [minbrowser/min#205] opened 2016-06-18 22:27 UTC
After a few mins of use (15-30), Min looses its preferences settings, which includes adblock and search engines.

You can retick adblock, but it doesn't stay ticked. When you try to reselect a search engine, none appear. Also, the no-script, no-image settings and keyboard shortcuts disappear altogether...

It does this regardless of which search engine you choose (I tried both the default and Yahoo).

The only way to fix this is to delete .config/min in the Home folder and start again. 

Using 1.3.1 with LM17.3 and LM18 Beta.

This pic is what I see when I loose the settings.
![screenshot from 2016-06-19 10-21-00](https://cloud.githubusercontent.com/assets/4667405/16174074/5be001d8-3608-11e6-9f8a-00b2a9d0205d.png)

**Comment by PalmerAL** [comment] 2016-06-20 22:30
Are there any errors in the console when this happens?

I can't reproduce this, and I'm not really sure why this would happen.

**Comment by baldrick-nz** [comment] 2016-06-21 07:35
Oddly enough it's not been doing it today. I'll check next time though...

**Comment by baldrick-nz** [comment] 2016-07-04 07:59
I've worked it out. This happens when one has multiple instances of Min open at the same time. All concurrent instances loose the ability to search (as noted above). The original instance continues as per usual.

If all instances close, and Min is relaunched all seems to work as expected.

No message appears in the console.

Hope that helps...

**Comment by PalmerAL** [comment] 2016-07-10 20:37
I can reproduce this on OS X.

I think this has to do with Chromium's indexedDB implementation. When a second instance is opened, opening the database fails, so settings, history, bookmarks, etc. don't work.

**Comment by KagamineP** [comment] 2020-07-20 08:12
I think this outdated, so I close this now. Feel free to reopen issue,

**Closed by KagamineP** 2020-07-20 08:12 UTC
Labels: bug
