### ISSUE TITLE
Can't restore previous session

### ISSUE THREAD

**Issue by code-hunger** [minbrowser/min#393] opened 2017-09-03 18:43 UTC
I just lost *all* my open tabs and I don't see any way to restore them.

I was reorganizing my tabs. When trying to release a tab after I had dragged it to the desired place, it got stuck to my cursor. I closed the task overlay but it still stood there. The button for the taskoverlay was still blue though. I closed the window and started min again. There was a single blank tab and I couldn't open the taskoverlay. I restarted the browser again, it worked now but everything was gone.

This is not the first time this happens to me, and I'm thinking of stopping using min as my main browser as it's just too unreliable.

**Comment by doreminiature** [comment] 2017-09-03 18:45
Yes, there is a need of sessions backup mechanism for sure.

**Comment by PalmerAL** [comment] 2017-09-03 18:59
Hmmm, you're probably right. We currently attempt to restore, and if the restore fails, we just start over with a blank set of tabs. We should probably try to instead display something like firefox's "Well, this is embarrassing" page (http://techdows.com/wp-content/uploads/2014/05/Firefox-restore-session-embarrassing-message.png), or at least write the data to a backup file somewhere.

**Comment by PalmerAL** [comment] 2017-09-03 19:04
In the meantime, do you have a backup of your computer? If you do, you should be able to restore ~/Application Support/Min (on macOS) or /home/<username/.config/Min (on Ubuntu, I think most other distros are pretty similar).

I really apologize that this happened; I'm going to add a basic backup mechanism in 1.6.1, and hopefully something more complete like Firefox in 1.7.0.

**Comment by code-hunger** [comment] 2017-09-03 20:27
I must think before act... to blindly close the non-responding window was completely stupid. I should've copied the config folder before that - I think it overwrote it after the window closed.  
No need to apologize, it's my fault I was so careless :D

Anyway, I'd suggest you instead of making backups (which I don't think makes much sense for a browser), you should try to avoid saving the session if it was not opened correctly. Or best - ask the user what to do.

**Comment by code-hunger** [comment] 2017-09-03 20:37
Another issue which I found some time ago is that the task overlay is just *an illusion*. In fact, the webpage "behind" is still there, and it receives all keyboard focus. I discovered this when I was trying to make the overlay keyboard-responsive by adding shortcuts and stuff. I gave up then as it seemed quite hard to make it as I want.

**Comment by PalmerAL** [comment] 2017-09-03 20:41
No, it's really my fault this happened. Restarting the browser when it fails to start seems like a logical thing to do, and Min really shouldn't delete your data without asking.

What I have right now attempts to restore the previous tabs when the browser starts. If an error occurs at any point during the process, it makes a copy of the corrupted data, saves it on your computer (so you can attempt to recover it later), and then displays this:

![screen shot 2017-09-03](https://user-images.githubusercontent.com/10314059/30006434-f9801142-90bd-11e7-94a2-2123f1f44d13.png)

This way, you can either close the error screen and keep browinsg with a new session, or go to the file path indicated and try to fix your saved data.

Ideally, there would be some kind of process that would automatically detect errors in the saved data and repair it for you, but I'm not sure how that would work.

**Comment by PalmerAL** [comment] 2017-09-03 20:43
About the task overlay, I think that's issue #357.

**Comment by PalmerAL** [comment] 2017-09-05 22:58
The basic functionality mentioned above is in 6d5b12476e8e4b9c7a2a466964d6c70ce23c0c49, it will be included in 1.6.1.

**Comment by PalmerAL** [comment] 2017-09-06 22:06
1.6.1 has been released.

**Comment by code-hunger** [comment] 2017-12-25 20:59
I got this error again - this time with a 34K json backup :D  
The same happened as before - when rearranging tabs, one of them got stuck to the mouse cursor. When l left the task overlay, I got a blank page with a single tab in the tabbar. The UI was not responding and the only thing I could do was to close the window. Is there anything I could do to restore my session?

**Comment by PalmerAL** [comment] 2017-12-25 22:41
You'll have to repair the backup file so that Min can understand it. Open the file in a text editor, and see if you can find anything that looks corrupted. In particular, look for anything with a value of "null" or "undefined". If you're willing too, you could also post the backup file here, although depending on what tabs you had open you may not want to do that.

Once you've repaired the backup file, open Min and run this in the browser devtools:

localstorage.setItem('sessionrestoredata', `insert the contents of the file here`); window.location.reload();

**Comment by code-hunger** [comment] 2017-12-25 22:54
Thanks! There are no undefined values but the names of all tasks are `null`. And, in the console there's the respective error:

```
restoring session failed:  TypeError: Cannot read property 'tabs' of null
    at Object.setSelected (build.min.js:4)
    at switchToTask (build.min.js:3)
    at Object.restore (build.min.js:6)
    at build.min.js:6
restore @ build.min.js:6
```

I'll set some arbitrary names for the tasks are will update here.

**Comment by PalmerAL** [comment] 2017-12-25 23:09
The task names are expected to be null, unless you've manually entered a name for them. Based on the error, I'm guessing that the value of the selectedTask property is referencing a task that doesn't exist in the list of tasks - could you look through your task list and try changing selectedTask to one of those IDs?

**Comment by code-hunger** [comment] 2017-12-25 23:20
Definitely, the value for `selectedTask` in json didn't match any of the tasks. I put there an existing value, ran the command you gave above and got the session restored.  
Thank you very much and Merry Christmas! :)

(I think this would be an easy problem to fix automatically)

**Comment by PalmerAL** [comment] 2017-12-26 00:18
I'm glad it worked, and Merry Christmas to you as well! I'll look into this some more soon.

**Comment by PalmerAL** [comment] 2017-12-26 21:41
I think I've figured it out: if you delete the currently-selected task (either by clicking the delete button or by dragging the last tab out of it), and then try to drag any other tab, it will break. I'll fix this in a few days; in the meantime, you can work around it by closing and reopening the task overlay after you delete the current task.

We could look into automatically detecting this and fixing it on startup, but I'd prefer to not have the data be corrupted in the first place.

**Comment by code-hunger** [comment] 2017-12-26 22:28
> and then try to drag any other tab, it will break

Why would it break? What does tab reordering *of other tasks* have to do with the currently selected task? It shouldn't be a UI issue at all.

Or, more generally: why would any actions on the task overlay be related to the current task or its absence?

**Comment by PalmerAL** [comment] 2017-12-26 22:47
What happens is this:

* To store the tab state, we have an object that looks like this:
```
{
  selectedTask: <some id>,
  tasks: [id: , name: , tabs: []]
}
```
* When you delete a task from the task overlay, we delete the task from the tasks array, but we don't update selectedTask (this is the bug!). Then, when you close the task overlay, we switch to the task you clicked on,  which will update selectedTask. However, until you close the task overlay, selectedTask will reference a task that doesn't exist any more.
* When you drag-and-drop a tab, we update the tab state to match what you just did. To do this, we do the following (the code for this is here: https://github.com/minbrowser/min/blob/master/js/taskOverlay/taskOverlay.js#L134):
  * Record the current selectedTask, and separately store a list of every tab currently open (URL, title, etc.)
  * Destroy the current tab state.
  * Loop through each tab  and task element displayed in the overlay, get the ID those elements correspond to, and rebuild the tab state based on that.
  * Set selectedTask to the task that was selected in the old model.

The problem is in the last step: we're resetting the selectedTask to it's value from before syncStateAndOverlay was called, but if you've deleted the currently-selected task in the overlay, then selectedTask is going to be a task that doesn't exist any more. So we'll end up calling tasks.setSelected with a task that doesn't actually exist, which throws an error. This error moves up th stack - syncStateAndOverlay will throw an error, which in turn breaks the drag-and-drop library we're using. This results in a broken UI, and when you reload the browser, the saved state will be broken as well.

The fix to this is going to be that, whenever we delete the currently-selected task, we need to pick another task to switch to immediately, instead of waiting until you close the task overlay.

**Comment by code-hunger** [comment] 2017-12-26 23:19
Looks too complex to me for a simple re-arrange of tabs ;)

On tab drag-n-drop, shouldn't we just remove the tab from its current position (`splice(index, 1)`) and push it to the new position (on a new task object, if needed)? 2 lines of code. And another two to remove the moved-from task in case this was the last tab in it.

Then the task-remover would be responsible about fixing the `currentTask` reference and this would make it very simple to implement a TaskClose keyboard shortcut. 

What do you think about such a design? My mind explodes when it tries to parse the 60-line long `syncStateAndOverlay` function and tell in two words what it's doing :D It goes too far away from *one function one thing* - a very good rule, IMO.

**Comment by PalmerAL** [comment] 2017-12-30 22:13
Yeah, that makes sense. I feel like there was some reason I didn't do that originally, but I can't remember what it was, so I'll change it to the simpler design like you suggest.

**Comment by PalmerAL** [comment] 2017-12-30 23:17
The actual bug is fixed in 973b94c5b08e4a72a980582ab60e8c86b9aaa197, next step is to get rid of ```syncStateAndOverlay```.

**Comment by PalmerAL** [comment] 2017-12-31 18:06
I've removed syncStateAndOverlay and replaced it with the design you suggested in 7efef2aadd9730f8472a0a6453471c1b583cd4c6. The new function is 30 lines long, and is definitely much simpler! Please file issues if you notice any bugs with the new implementation.

**Comment by PalmerAL** [comment] 2018-05-05 19:13
Hmm, I'm sorry that happened. I've looked through the session restore code again, and I'm not really seeing how this could occur. Assuming you're on the 1.6.1 branch or later, you should have seen an error screen instead - if you're seeing the tour screen, that means we don't have any saved data at all, but it sounds like that's not what happened. If you were on an older branch, it would make sense that the tour screen would show up, but then you also wouldn't have had a backup file, which it sounds like you did. I'm also not really seeing how selectedTask could point to a tab - we don't set that property in very many places, and as far as I can tell we use a task ID in all of them.

Was there anything in particular you were doing before this happened?

Some kind of way to recover from the backup file would be nice, but I'm not really sure how it would work. If we've created the backup file, then the data is corrupted somehow, and I'm not really sure there's any way to reliably detect whats wrong.

**Comment by code-hunger** [comment] 2018-05-05 19:34
It happened after I tried to fix a merge conflict when making the PR about error pages. I hadn't pulled for quite a while and I also tried to clean all the fake commits that appear on my PR so I did a few times rebases & merges, all of which I `--abort`ed at some time. In the meantime I was `grunt`ing to check if it worked.

At some point I got an error about a missing npm module, so I ran `npm i`. This downloaded electron and built min as a binary. Next, when I started min with `electron .` I got the welcoming screen (all history, settings & tab state gone), while starting the binary still opened my tabs. After a few tries I ran `npm i` again but this time it didn't build min as a binary so I ran `grunt linuxBuild`. I think this last the last moment before my tab state was totally lost (except for the backup, for which though I'm unsure whether it wasn't an older one and not freshly created).

It is not normal behaviour for a standard user :smile: so I think it's not *that* impossible to happen.

**Comment by PalmerAL** [comment] 2018-05-06 22:45
That's strange. I think what might have happened is that you opened two instance of Min at the same time. If you do that, the second instance can't access the database, so you won't have any of your data, and it will start with just the welcome screen. I think if you then close the other instance, it might be able to write the tab set it currenty has (which is just the welcome screen) back to localStorage and overrwrite your data that way, but I'd have to test that to be sure. The other option is that you ran Min with a newer version of Chromium and then downgraded to an older one; I think they changed the storage format recently, so downgrading will corrupt your data.

(And neither of these scenarios would generate a backup file, so either the file you restored from was an old one or there's something else happening).

A warning about running multiple instances was added in aa05ff4795913e02f0b3cf2313b8b731e008ce08; although this is reminding me that we should probably quit the app after showing the warning. I guess that would probably fix the first scenario, although it wouldn't do anything for the second.

**Comment by code-hunger** [comment] 2018-05-07 15:01
Yeah, at some point I did open a second instance but I've already forgotten what exactly did I do before that. I remember though for sure that the first instance was showing tabs correctly.

I think this explains the situation. Sorry that I forgot to mention that earlier. 

I got a popul telling me to close min but I didn't comply with it. Should have done so, though.

**Comment by PalmerAL** [comment] 2018-05-12 02:01
I've changed the warning so that the app will automatically quit after you click the OK button in 5063a3ff3fb16829b4b873786c77091590bde802; I think this should hopefully address the situation. 

Since the original issue (with drag-and-drop corrupting the tab state) seems to be fixed, I'm going to close this issue, but please open a new issue if you see any more problems.

**Closed by PalmerAL** 2018-05-12 02:01 UTC
