### ISSUE TITLE
Hang when modifying certain settings

### ISSUE THREAD

**Issue by Andrey6777** [minbrowser/min#1559] opened 2021-04-11 00:08 UTC
When you uncheck the "send usage statistics" checkbox, strong lags start in the browser. When you check the box back, the lags pass, but the settings are also reset to the previous or standard ones.

**Comment by PalmerAL** [comment] 2021-04-11 06:25
That's very strange. Can you upload a performance profile so we can see why it's lagging?

1. Disable usage statistics, and make sure you're seeing lag.
2. Go to developer > inspect browser > performance.
3. Click "record".
4. Use the browser for ~30 seconds, and do things that cause lag.
5. Click "stop", then click the download arrow in the top-left.
6. Upload the resulting file here.

Thanks!

**Comment by shushtain** [comment] 2021-04-11 09:40
![image](https://user-images.githubusercontent.com/58133782/114299212-ca1a8280-9ac2-11eb-8dd1-6b849a766f8c.png)
That's what happens in this case, just like in mine (#1558).
There is something wrong in the processing of settings, not just because of multiple shortkeys.

**Comment by Andrey6777** [comment] 2021-04-11 15:51
> That's very strange. Can you upload a performance profile so we can see why it's lagging?
> 
> 1. Disable usage statistics, and make sure you're seeing lag.
> 2. Go to developer > inspect browser > performance.
> 3. Click "record".
> 4. Use the browser for ~30 seconds, and do things that cause lag.
> 5. Click "stop", then click the download arrow in the top-left.
> 6. Upload the resulting file here.
> 
> Thanks!
Sorry, 
I cannot do this, from lags. Browser actually freezes.

**Comment by PalmerAL** [comment] 2021-04-11 22:19
OK, I can reproduce. It looks like we get stuck in an infinite loop of `settings.updateChangeCallbacks`.
I think this was actually fixed already by 0d20133d6e4df3ff170c68e9f04c19c7e87f9470, but I haven't confirmed that.

**Comment by PalmerAL** [comment] 2021-04-11 22:21
Turned off update notifications until this is fixed: https://github.com/minbrowser/min/commit/9f6d3958ed67edc1cdb1eb026dd8a956992756d2

**Comment by PalmerAL** [comment] 2021-04-12 06:33
I think 3775365834a1f2e1db48019bd53407645e73881a should fix this; I'm going to test it for another day and then make a new release. It would be great if you could test it as well, but it's fine if you can't.

**Comment by PalmerAL** [comment] 2021-04-12 21:55
@Andrey6777 This should be fixed in v1.19.1; can you try installing that and confirm that it fixes the issue?

**Comment by Andrey6777** [comment] 2021-04-13 18:12
> @Andrey6777 This should be fixed in v1.19.1; can you try installing that and confirm that it fixes the issue?

I tested it, everything works amazingly. I did not see any bugs, and I did not see any errors. Thank you

**Comment by Andrey6777** [comment] 2021-04-13 18:14
And so on, the RAM consumption has decreased a little

**Comment by PalmerAL** [comment] 2021-04-13 21:53
Great!

**Closed by PalmerAL** 2021-04-13 21:53 UTC
Labels: bug
