### ISSUE TITLE
Is there a youtube download extension for Min?

### ISSUE THREAD

**Issue by Textmail** [minbrowser/min#732] opened 2019-04-14 19:18 UTC
I really like Min, and it would be great to have a youtube downloader. Thanks. Texting.

**Comment by PalmerAL** [comment] 2019-04-15 03:16
I'm not aware of one, but you could probably create a [userscript](https://github.com/minbrowser/min/wiki/userscripts) to do that.

**Comment by Textmail** [comment] 2019-04-15 04:36
Dear PalmerAL,

Thanks very much for your rapid response.

Am not a tech person, so no idea

how to do that - found Min somehow,

and very much like it.

 

Thanks again.

Stan

 

Gesendet: Montag, 15. April 2019 um 05:16 Uhr
Von: "PalmerAL" <notifications@github.com>
An: minbrowser/min <min@noreply.github.com>
Cc: Textmail <textmail@gmx.ch>, Author <author@noreply.github.com>
Betreff: Re: [minbrowser/min] Is there a youtube download extension for Min? (#732)


I'm not aware of one, but you could probably create a userscript to do that.

**Comment by dbfreem** [comment] 2019-07-15 10:34
Since this is a duplicate of #1 I am going to close it.

**Closed by dbfreem** 2019-07-15 10:34 UTC
