### ISSUE TITLE
alt-tab

### ISSUE THREAD

**Issue by LukaFX** [minbrowser/min#689] opened 2018-12-31 20:33 UTC
when you alt-tab from another windown to min the right click meno automaticly opens were the mose is, its kinda annoying.

**Comment by PalmerAL** [comment] 2019-01-02 23:16
I can reproduce this if I click on the Min window in the alt-tab window, and then release the alt key. This is probably because of 37d474421d88eebc515822db2ebbbce2dea0661e; we need to check for both a keydown and a keyup event (or just disable the alt shortcut on Windows entirely, I'm not sure that it makes sense now that we don't have a traditional menu bar).

**Comment by PalmerAL** [comment] 2019-10-13 06:25
This was fixed in the latest release.

**Closed by PalmerAL** 2019-10-13 06:25 UTC
Labels: Windows, bug
