### ISSUE TITLE
A few problems

### ISSUE THREAD

**Issue by vnvyvu** [minbrowser/min#664] opened 2018-11-08 14:18 UTC
1. I can not watch video on Facebook (the whole is green)
2. I can not watch videos on Youtube
3. If possible, add site translation functionality

**Comment by PalmerAL** [comment] 2018-11-09 04:06
> I can not watch video on Facebook (the whole is green)

Does the same thing happen in Chrome?

> I can not watch videos on Youtube

Do Youtube display any kind of error message? If you go to developer menu > inspect page > console, are there any error messages?

> If possible, add site translation functionality

This would be cool, although I'm not sure if there are any translation services that have a free API (and have an acceptable privacy policy, etc). Its definitely worth looking into though.

**Comment by KagamineP** [comment] 2020-07-19 11:49
I can't reproduce this, so I closing this now. Feel free to reopen it.

**Closed by KagamineP** 2020-07-19 11:49 UTC
