### ISSUE TITLE
New feature idea

### ISSUE THREAD

**Issue by MattTheMaker** [minbrowser/min#932] opened 2020-03-11 18:11 UTC
I love Min, and the idea of a totally minimalistic web browser like this, not to mention Min is the best one of it's kind out there, but I think it could really do with a default webpage setting. For example, I open Min to be greeted to my Email, instead of a new tab. As far as I can see, there is no way to do this, but I could be wrong.

**Comment by PalmerAL** [comment] 2020-03-12 00:48
Duplicate of #327.

There's a workaround where you can change [this line](https://github.com/minbrowser/min/blob/master/js/tabState/tab.js#L10) to this:
```
      url: tab.url || 'http://example-homepage.com',
```
and build Min yourself if you're willing to do that.

**Closed by PalmerAL** 2020-03-12 00:48 UTC
