### ISSUE TITLE
Momentum scrolling and Command key (⌘) causes accidental zoom

### ISSUE THREAD

**Issue by CydeSwype** [minbrowser/min#550] opened 2018-04-22 17:17 UTC
Often I scroll down a page and then begin to open a new tab (or perform some other keyboard shortcut that involves using the command key).  The default touchpad behavior for Mac is to use momentum scrolling so that two finger swipes continue scrolling up/down a page.  If the page is still scrolling (due to this momentum) when the command key is pressed, the browser interprets this as a zoom instruction (command + swipe down/swipe up zooms page content in/out).

Other browsers seem to avoid this accidental behavior (they ignore the command key if it was pressed after the beinning of the scroll).  A simple fix would be to remove/ignore this keybinding since users have other methods of zooming (i.e. cmd+"plus").

**Comment by PalmerAL** [comment] 2018-04-23 03:01
Duplicate of #89. I'm currently working on implementing the first solution you mentioned in #534, it should be finished by the time 1.8.0 is released.

**Closed by PalmerAL** 2018-04-23 03:01 UTC
