### ISSUE TITLE
Min crashing sporadically across OSes

### ISSUE THREAD

**Issue by Lacedaemon** [minbrowser/min#872] opened 2019-12-10 04:47 UTC
Hello,

I was waiting it out to see if this would be fixed in a later commit, but it's gotten to a point where Min's stability is so shaky, I've gone back to using the default browser for important stuff.

I wish I could provide some level of reproducibility, but the crashes aren't really consistent.  For example, I'll open YouTube, and it'll crash; when I open the browser back up to YouTube, everything's fine.  Same with opening new tabs.

I've attached two logs from two different times it crashed.  What I immediately noticed is that the exception types, codes, etc are the same.  Hopefully this can provide some clue(s) as to what's causing the crashes.

[Min Crash 0.log](https://github.com/minbrowser/min/files/3943064/Min.Crash.0.log)
[Min Crash 1.log](https://github.com/minbrowser/min/files/3943065/Min.Crash.1.log)

* OS: Windows/macOS/Linux
* Hardware
  * Desktop: i7-9800X
  * Laptop: i5-8250U
* Min version: latest from source

Steps taken to compile:

1. Change version in package.json to 1.11.2
2. `npm install; npm run buildMac`

**Comment by PalmerAL** [comment] 2019-12-10 21:10
This looks the same as electron/electron#20773; I can reproduce that by opening a new private tab, and then closing it without loading a webpage. Does that match what you're doing? If that's the only case where this happens, I think we can work around it by loading an empty local file as soon as the tab is created, but if it's happening in other situations we'll most likely need to wait for a fix in Electron.

**Comment by Lacedaemon** [comment] 2019-12-11 18:05
That would definitely check out, since I do open a lot of private tabs and then change my mind.

However there have also been times where it would crash on loading some sites, e.g. YouTube.

Again I apologize that I can't provide better reproducability.

**Comment by PalmerAL** [comment] 2019-12-12 03:57
The crash happens during the next garbage collection, which is usually a bit after you close the tab, so that could explain why it seems to be crashing later.

I've added a workaround (f387d7f6111c782630e313be457f35b44519e520) that I think prevents the crash from happening, could you try rebuilding and see if you get any more crashes?

**Comment by Lacedaemon** [comment] 2019-12-12 05:00
I'll recompile and trial it on all my machines (and hopefully other OSes).  Thanks for looking into this!

**Comment by Lacedaemon** [comment] 2019-12-14 18:16
Well, I gave it a couple days, and the crashes definitely would've happened by now without the patch.

Thank you very much, confidence in Min restored!

**Comment by PalmerAL** [comment] 2019-12-15 22:52
I'm glad it worked! I'll leave this issue open for now in the hope that this will eventually be fixed in Electron so I can remove the workaround.

**Comment by PalmerAL** [comment] 2019-12-25 04:57
I'm still seeing this occasionally even with the workaround.

**Comment by Lacedaemon** [comment] 2020-01-02 18:07
I wanted to test a bit more before responding, but yes, though the frequency of the crash has reduced, it still happens occasionally on my end as well.

**Comment by akapitoha** [comment] 2020-11-05 19:45
also getting crashes in private mode on Mojave. Min 1.16.1

**Comment by PalmerAL** [comment] 2020-11-05 23:59
This issue's old enough that it may not be related, can you make a new one? Do you have a crash report?

**Closed by PalmerAL** 2020-11-05 23:59 UTC
Labels: OS/Mac, bug
