### ISSUE TITLE
Windows: Not launching in fullscreen

### ISSUE THREAD

**Issue by AluminiumTech** [minbrowser/min#214] opened 2016-07-23 15:59 UTC
Hi,
I tried out Min and I found that the Windows version isn't launching in fullscreen properly. 
IDK if this is by design or not but it's not going fullscreen. It's almost the same as being fullscreen except it's not fullscreen and it's annoying.
You can see in the right hand side and on the bottom how it isn't fullscreen. Please fix this.
Thanks.

![screenshot](https://cloud.githubusercontent.com/assets/14107316/17078865/2eaae022-50ff-11e6-9c06-55a914e49e11.PNG)

**Comment by PalmerAL** [comment] 2016-07-23 23:17
This is caused by https://github.com/electron/electron/issues/4045.

I've added a workaround for this in ed4e11f296cf921400f325207faffbd430b8d930. It will be included in 1.4.1, which will be released in a few days.

**Comment by PalmerAL** [comment] 2016-07-26 23:01
@AluminiumTech Can you confirm that this is fixed in 1.4.1?

**Comment by AluminiumTech** [comment] 2016-07-27 13:33
Unfortunately no. I've just tried it and it hasn't been fixed.

![new screenshot](https://cloud.githubusercontent.com/assets/14107316/17176977/65b49348-540f-11e6-9055-7d1122b38c6c.PNG)

**Comment by PalmerAL** [comment] 2016-07-30 02:06
Hmmm, it works for me now.

Are you using Min 1.4.1 (from here: https://github.com/minbrowser/min/releases/tag/v1.4.1)? Also, which version of Windows 10 are you using?

**Comment by AluminiumTech** [comment] 2016-08-07 10:43
I was using Windows 10 November Update (version 1511). 

The issue seems to be fixed now that I'm using the Anniversary update (version 1607).

Thanks

**Closed** 2016-10-15 01:38 UTC
Labels: bug, Windows
