### ISSUE TITLE
Add a way to change the user agent

### ISSUE THREAD

**Issue by dbfreem** [minbrowser/min#657] opened 2018-11-04 10:37 UTC
When I tried to log into the yahoo mail webpage, I received a popup saying that my browser did not support yahoo mail.

**Comment by PalmerAL** [comment] 2018-11-07 08:44
I don't have a Yahoo account to test this, but I'm guessing they're probably just checking the user-agent and blocking anything that's not Chrome... there's not really anything we can do about this, although I guess we could use a fake UA just for that site.

The other alternative is Yahoo Mail requires support for popup windows (which we don't implement fully), although I'm not sure why that would be the case.

**Comment by dbfreem** [comment] 2018-11-10 00:17
Below is the popup that I see when trying to goto the yahoo mail box. Also, if you click on the continue to classic mail the popup just comes up again. 

![image](https://user-images.githubusercontent.com/9778569/48294689-d1ea1e80-e453-11e8-9062-c7b76e6b13a4.png)

**Comment by apm** [comment] 2018-11-10 00:19
What is the reported UA?  UA manipulation is probably a fundamental need for a fringe browser.  Per site UA would be a useful feature.

**Comment by dbfreem** [comment] 2018-11-10 01:03
so when I looked at the source of the page there was some javascript that referenced "browserName":"Electron"

**Comment by dbfreem** [comment] 2019-01-05 23:53
@PalmerAL For what it is worth. I went back to yahoo in Min today. I set my user agent in the developer tool to chrome windows. Then I logged in. Everything seemed to work fine when the user agent was changed to chrome windows.

**Comment by PalmerAL** [comment] 2019-01-06 19:11
@dbfreem Good to know, changing the UA for that website sounds like a good solution then.

**Comment by PalmerAL** [comment] 2019-01-08 23:55
I'm going to start making a list of site that need this, so we don't forget any when we implement this:

* mail.yahoo.com
* medium.com
* web.whatsapp.com
* fiverr.com

**Comment by PalmerAL** [comment] 2019-01-12 05:55
I attempted to start implementing this, and I've run into a bit of an issue. My original plan was to listen for ```did-start-navigation``` events, and then switch to the Chrome UA depending on the URL that is being loaded. However, when you change the user agent, Chromium stops loading the new page, and reloads the existing page instead because of this code: https://cs.chromium.org/chromium/src/content/browser/web_contents/web_contents_impl.cc?sq=package:chromium&g=0&l=1272

I think we can probably cancel the existing page load, switch the UA, and then start a new page load, but I'm not sure if there's any other issues that this might cause.

**Comment by PalmerAL** [comment] 2019-01-13 03:53
Cancelling and reloading the page prevents the back button (and the associated shortcuts) from working correctly, so that probably isn't an option.

One other thing we could consider is just using the Chrome UA everywhere. This would make it difficult to implement any Min-specific behavior on your website, but I doubt anyone's doing that anyway, so I wouldn't expect that to be an issue. Doing this would also be good for fingerprinting resistance, which is a nice bonus.

**Comment by PalmerAL** [comment] 2019-01-23 03:51
I've changed the user-agent to match Chrome's for all pages in ea1cd2b2f4aea0dffceebc7292b172e9c4dd5e13. @dbfreem Could you make sure that Yahoo Mail works now in the default configuration?

**Comment by dbfreem** [comment] 2019-01-23 03:55
@PalmerAL I will take a look at this tomorrow. Thanks.

**Comment by dbfreem** [comment] 2019-01-28 02:12
@PalmerAL I checked this with Yahoo mail and it works.

**Comment by Figuera** [comment] 2019-02-05 22:01
Is the fix available on version 1.9.0 for windows? Web Whatsapp is working for me but just for the first time I use it, if I close the browser and try to open it again it complains about my "chrome version". I can still use it on private mode, but having to login every time I use it is very troublesome. Is there any suggestion on how to proceed?

PS: By the way can't I delete my cookies?

**Comment by PalmerAL** [comment] 2019-02-06 00:11
Interesting, I can reproduce that as well. It looks like there's something odd happening with how `setUserAgent` works with service workers.

The default user agent string contains both "Min" and "Electron" components:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Min/1.9.0 Chrome/69.0.3497.106 Electron/4.0.4 Safari/537.36

We replace it with a string that contains neither:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.106 Safari/537.36

But at some point in the process of loading https://web.whatsapp.com/serviceworker.js, the "electron" part gets added again:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.106 Electron/4.0.4 Safari/537.36

I guess I need to track down the code in Electron that's responsible for setting the user agent, and see why this is happening.

You can delete cookies by going to developer > inspect page > application > "clear site data".

**Comment by PalmerAL** [comment] 2019-04-28 17:38
It looks like we'll be able to fix the whatsapp issue once electron/electron#18016 is merged.

**Comment by dbfreem** [comment] 2019-05-28 02:53
@PalmerAL  looks like that commit from electron merged to master a few weeks back. I am assuming next time Electron is updated you will get this change??

**Comment by PalmerAL** [comment] 2019-05-28 22:25
I think so, yes (probably in Electron 6.0).

**Closed** 2019-08-16 22:23 UTC
