### ISSUE TITLE
Can't log in to certain sites

### ISSUE THREAD

**Issue by BenTearzz** [minbrowser/min#800] opened 2019-08-03 22:45 UTC
So, for example, if you go to https://mixer.com/ and try to login with Microsoft, with browsers like Chrome or Firefox it comes with a popup login box, but not in Min, in Min it opens a blank tab and that's it. This is probably because you're not able to have multiple Min browser windows open.

I can't login on sites like Khan Academy either, because when I click "Login with Google", it opens a new tab (like it should), then sends me back to the Khan Academy homepage, making it impossible to login. But it doesn't do this in other browsers.

**Comment by dbfreem** [comment] 2019-08-04 00:59
This sounds the same as #140 . We should probably combine all the popup issues into #140 .

**Comment by dbfreem** [comment] 2019-08-07 02:31
duplicate of #140

**Closed by dbfreem** 2019-08-07 02:31 UTC
