### ISSUE TITLE
feedly not logging in

### ISSUE THREAD

**Issue by jojoman02** [minbrowser/min#240] opened 2016-08-19 21:06 UTC
loging in thru google at feedly.com doesn't work.

**Comment by PalmerAL** [comment] 2016-08-20 19:00
This is probably because Min doesn't support popup windows, which is #140.

**Comment by Sestowner** [comment] 2020-07-20 08:21
I can't reproduce this, so I'm going to close this issue. Feel free to reopen this if you have the problem again.

**Closed by Sestowner** 2020-07-20 08:21 UTC
