### ISSUE TITLE
microphone request icon does not show up sometimes

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1073] opened 2020-06-18 12:55 UTC
I had this happen on almost all websites. I think i found exact steps, here is how it happens

1. opening this [website](https://www.onlinemictest.com/) and press "play" icon, this is when the website requests for mic permission and icon shows up in the tab.
2. reload page without giving permission
3. press "play" again and the mic icon does not show up, unless i go to different Task and then come back

and thats not all, it also happens by some other steps but the above steps reproduce the problem always for me...

and also this steps sometimes cause it:

1. opening this [website](https://www.onlinemictest.com/) and press "play" icon
2. give permission
3. revoke permission
4. press "play" again and the icon doesnot show up again

**Comment by BenStigsen** [comment] 2020-06-18 13:45
I cannot reproduce this. (I'm using version 1.15)

**Comment by PalmerAL** [comment] 2020-06-18 16:30
I can't reproduce either on macOS 10.14. @shalva97 Which OS?

Revoking permission reloads the page, so it's possible there's a timing issue here (maybe depending on the speed of your internet connection).

**Comment by shalva97** [comment] 2020-06-18 21:45
i feel dumb now, cannot reproduce it also. Maybe because i restarted my PC... also didnot knew revoking permission reloads page, it was too fast for me to notice, my internet is 30mbps

 anyways as i remember it happened after some1 calling in Slack, but im not sure... will post update if i encounter it again

OS: Arch Linux
Min: 1.14.1

**Comment by PalmerAL** [comment] 2020-06-22 22:09
I'm going to close this for now, but please do make another issue if it happens again. (And if it happens, check the browser console and see if there are any errors listed there).

**Closed by PalmerAL** 2020-06-22 22:09 UTC
Labels: bug
