### ISSUE TITLE
Future Plans to integrate a "Open new Window" option?

### ISSUE THREAD

**Issue by thanhtientc** [minbrowser/min#341] opened 2017-04-12 17:12 UTC
Hi I love using the browser but wanted to ask if it's possible or planned to add a "open in new Window" feature? Would be useful for working on multiple monitors for instance.

**Comment by PalmerAL** [comment] 2017-04-16 16:21
This is a duplicate of issue #169.

**Closed by PalmerAL** 2017-04-16 16:21 UTC
