### ISSUE TITLE
Some buttons in discord website are not working

### ISSUE THREAD

**Issue by VasylTyshchuk** [minbrowser/min#1425] opened 2021-01-11 17:10 UTC
- Min version: 1.17.3
- Operating system: Windows 10 x64

Red line - these buttons don't work at all
Yellow line - these buttons almost don't work

![image](https://user-images.githubusercontent.com/71596800/104214756-87ec9100-5440-11eb-85ba-7018c9872835.png)

P.S. Everything works fine in Mozilla and Microsoft Edge

**Comment by PalmerAL** [comment] 2021-01-11 20:32
Duplicate of #1381.

I think this might be fixed in the next release once we upgrade to a newer version of Electron; can you try it then and let me know if it's still not working?

**Closed by PalmerAL** 2021-01-11 20:32 UTC

**Comment by VasylTyshchuk** [comment] 2021-02-20 08:07
Min version: 1.18.1 everything is working now
