### ISSUE TITLE
How to make linux browser look like windows version

### ISSUE THREAD

**Issue by idAlencar** [minbrowser/min#874] opened 2019-12-13 11:28 UTC
Hello, How can I change the appearance of the Linux browser to look like the version of Windows?

Thanks for your help, great project!

**Comment by PalmerAL** [comment] 2019-12-14 04:21
It's fairly simple to do this if you're willing to build Min yourself. I think this patch should be enough to get it to work, although I haven't actually tested it:

```diff
diff --git a/js/default.js b/js/default.js
index df806cf..0597c93 100644
--- a/js/default.js
+++ b/js/default.js
@@ -23,8 +23,8 @@ if (navigator.platform === 'MacIntel') {
   document.body.classList.add('windows')
   window.platformType = 'windows'
 } else {
-  document.body.classList.add('linux')
-  window.platformType = 'linux'
+  document.body.classList.add('windows')
+  window.platformType = 'windows'
 }
 
 if (window.platformType === 'windows') {
diff --git a/js/windowsCaptionButtons.js b/js/windowsCaptionButtons.js
index bf244f0..30bc12d 100644
--- a/js/windowsCaptionButtons.js
+++ b/js/windowsCaptionButtons.js
@@ -23,7 +23,7 @@ function updateCaptionButtons () {
   }
 }
 
-if (navigator.platform === 'Win32') {
+if (true) {
   updateCaptionButtons()
 
   captionMinimise.addEventListener('click', function (e) {
diff --git a/main/main.js b/main/main.js
index bbbb309..bab8901 100644
--- a/main/main.js
+++ b/main/main.js
@@ -123,11 +123,11 @@ function createWindowWithBounds (bounds, shouldMaximize) {
     height: bounds.height,
     x: bounds.x,
     y: bounds.y,
-    minWidth: (process.platform === 'win32' ? 400 : 320), // controls take up more horizontal space on Windows
+    minWidth: (process.platform === 'linux' ? 400 : 320), // controls take up more horizontal space on Windows
     minHeight: 350,
     titleBarStyle: 'hiddenInset',
     icon: __dirname + '/icons/icon256.png',
-    frame: process.platform !== 'win32',
+    frame: process.platform !== 'linux',
     alwaysOnTop: settings.get('windowAlwaysOnTop'),
     backgroundColor: '#fff', // the value of this is ignored, but setting it seems to work around https://github.com/electron/electron/issues/10559
     webPreferences: {
```

Also, what do you like better about the Windows UI than the Linux one?

**Comment by IdXs01** [comment] 2019-12-14 11:54
almost everything went well, only the minimize, maximize and close buttons did not appear, but the address bar worked perfectly

**Comment by IdXs01** [comment] 2019-12-14 11:56
What do you think of adding in the settings an option to choose the mode of operation? (Single bar and double bar mode)

**Comment by dj-sash** [comment] 2019-12-15 02:05
Hi… Anyone can give a guide how to make it look like Safari?
I am a designer, null in these coding stuff.
That would be a great help,
Thanks

**Comment by dj-sash** [comment] 2019-12-15 02:06
Hi… Anyone can give a guide how to make it look like Safari? I mean on Mac
I am a designer, null in these coding stuff.
That would be a great help,
Thanks

**Comment by PalmerAL** [comment] 2019-12-15 23:52
The window buttons show up for me, I'm not sure why they wouldn't be working for you.

I agree having some kind of integrated titlebar on Linux would make sense. The issue is that to do that, we can't use the native titlebar buttons, and there are so many different variations of titlebar layouts on Linux that whatever we do won't match other apps. I guess that could still be better than a two-bar layout though.

**Comment by IdXs01** [comment] 2019-12-16 11:25
I am using version 1.11.2-2 [community] from Arch repository, I edited the modifications directly in the / usr / lib / min / js files. Is it correct or should I go another way?

**Comment by PalmerAL** [comment] 2019-12-16 16:37
If you're editing the existing package, you would need to modify main.build.js and dist/bundle.js for it to work.

**Comment by Syndamia** [comment] 2020-08-27 11:30
@idAlencar how did it go? Were you able to get it working the way you want or did you give up?

**Comment by PalmerAL** [comment] 2020-08-30 03:21
Linux now uses the same integrated-titlebar UI as the Windows version by default, so I think it's fine to close this.

**Closed by PalmerAL** 2020-08-30 03:21 UTC
Labels: OS/Linux, question
