### ISSUE TITLE
Windows path + filename too long

### ISSUE THREAD

**Issue by usipeus** [minbrowser/min#47] opened 2016-04-16 18:43 UTC
Thanks for making Min, I think it's great! However, I tried extracting the Min-v1.1.2-win32-x64.zip file to C:\, but some of the folders and files have a path + filename length greater than what Windows 10 allows (either 256 or 260 characters, apparently). After skipping copying those files, Min seems to work normally.

Here's a few of the errors I got; there were more files and folders with long names that Windows couldn't handle so I had no choice but to skip copying all of them.

![min-win-error1](https://cloud.githubusercontent.com/assets/6962459/14582934/7e5a3074-03d8-11e6-9e03-a0221acb354f.PNG)

![min-win-error2](https://cloud.githubusercontent.com/assets/6962459/14582935/803d5826-03d8-11e6-8aa3-553fab0b9401.PNG)

**Comment by PalmerAL** [comment] 2016-04-16 20:44
The files you mentioned are all inside the node_modules folder. The problem is that most node modules are nested inside each other, so you end up with a path that's too long. Supposedly, npm 3 has fixed this by flattening the module list, so I guess I'll upgrade before I publish the next release.

If you want to build Min yourself, you'll need those files to be copied. Make sure you have npm 3 installed, then download a zip file from here: https://github.com/PalmerAL/min/archive/master.zip and then run ```npm install```.

**Comment by PalmerAL** [comment] 2017-11-11 23:38
This should be fixed now, since we're building with NPM 5, which doesn't do recursive directories any more.

**Closed by PalmerAL** 2017-11-11 23:38 UTC
