### ISSUE TITLE
selected tab behind "new task" button

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1342] opened 2020-11-16 14:17 UTC
* **Min Version:** 1.16.0
* **Operating system:** Arch

## Expected Behavior
if the selected tab is behind "new task" button, it should scroll

## Actual Behavior
it stays behind that big button

## To Reproduce
create lot of tabs until at least one tab will be under "new task" button and scroll position is top. then select it and when you reopen Task View it will stay behind the New Task button.

selected tab looks something like this
![image](https://user-images.githubusercontent.com/22417494/99262730-c1858f00-2837-11eb-83f7-fecff294db88.png)

**Comment by Milo123459** [comment] 2020-11-17 16:52
Try upgrading to 1.17.1

**Comment by Syndamia** [comment] 2020-11-17 17:15
Yeah, this is because the button is just on top of everything, the tasks and the button aren't two different sections of the screen.

**Comment by shalva97** [comment] 2020-11-17 18:33
Im using Arch package, which is slow on updates. but this issue should be in newer versions too...

**Comment by PalmerAL** [comment] 2020-11-22 06:27
Fixed in af5e079f60373882598ac904e2fdd897f818a32a.

This does create a small regression where the favicon gets cut off as you scroll:
<img width="1280" alt="Screen Shot 2020-11-22 at 12 21 58 AM" src="https://user-images.githubusercontent.com/10314059/99896776-5eda2c00-2c59-11eb-9b67-0669418bd870.png">
But I think that's probably an acceptable tradeoff.

**Closed** 2020-11-22 06:26 UTC
Labels: feature/preference
