### ISSUE TITLE
support linux package (flatpak)

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#635] opened 2018-10-04 05:26 UTC
I have a simple question.
I created this issue because I did not know how to contact.

---

Are you planning to distribute Min as a flatpak in the linux?
If possible, I hope Min will be distributed via flatpak.

**Comment by code-hunger** [comment] 2018-10-04 16:55
Due to being Electron based, Min doesn't have anything to be "installed" in the sense other packages are installed in directories like /usr/share, /usr/bin, /usr/lib, /etc, etc.

Flatpak provides a single interface for package installation on different linux distros, which is irrelevant to Min as Electron already takes care of that.

**Comment by Syndamia** [comment] 2020-07-26 16:31
Duplicate of #750 (*even though it was created before it :/*). Also Linux packages are discussed in #735.

**Closed by Syndamia** 2020-07-26 16:31 UTC
Labels: OS/Linux, status/duplicate
