### ISSUE TITLE
Ask for Access(not in MinBrowser)

### ISSUE THREAD

**Issue by CorbsEditor** [minbrowser/min#474] opened 2017-12-26 17:58 UTC
![1](https://user-images.githubusercontent.com/26362558/34361880-6475f214-ea3c-11e7-972c-292b60728c73.PNG)
Example Above ^

**Comment by PalmerAL** [comment] 2017-12-26 21:36
Duplicate of #332.

**Closed by PalmerAL** 2017-12-26 21:36 UTC
