### ISSUE TITLE
Can't authorize my github account to login into draw.io site.

### ISSUE THREAD

**Issue by manoger** [minbrowser/min#1256] opened 2020-09-29 13:36 UTC
* **Min Version:1.16**
* **Operating system:Windows 10** 

## Expected Behavior
Authorize GitHub app in draw.io site.

## Actual Behavior
"Service unavailable or blocked"
In another browser works.

## To Reproduce
1. Click "Open existing diagram"
2. Click in "Authorize"
3. Opens a new tab
4. "This window will be closed automatically." (the tab doesn't close automatically)
5. In draw.io "Service unavailable or blocked" (problem)

**Comment by Syndamia** [comment] 2020-09-29 19:28
I was able to replicate it (Linux), so at least the problem isn't related to operating system.

**Comment by PalmerAL** [comment] 2020-09-30 15:31
Duplicate of #140.

**Closed by PalmerAL** 2020-09-30 15:31 UTC
Labels: bug
