### ISSUE TITLE
clean up backlog of issues

### ISSUE THREAD

**Issue by dbfreem** [minbrowser/min#764] opened 2019-05-29 02:26 UTC
Somewhat Ironic that I created an issue for this haha. But I keep noticing how big the backlog of items are for min. I find it difficult to understand what the top priorities are with the random list of bug, enhancements, and thank you notes in the back log.

My personal opinion is that we should go through the back log and systematically clean it up. Below are some ideas. 

- Leave anything open that is classified as a bug

- Close "most" enhancement over 1 years old

- Prioritize the remaining backlog after the cleanup

- Review classifications such as OS, Bug, Enhancement, etc.

- Create an issue template for the repository so that all neccessary information is added on creation of the issue.

After thsis cleanup we would have a much clearer picture of what min is all about and what is the path forward. 

Thoughts!!!

**Comment by PalmerAL** [comment] 2019-05-29 22:43
In general, I think that's a good idea. I haven't been very motivated to go through and clean up everything - if you want to do that, I'd be happy to give you access to the issue tracker.

I'm not sure I agree that automatically closing old enhancements is a good idea - many of them are features that still haven't been added, and that do make sense to add. But it probably is worth reviewing them at least - if only a single person has requested something, and it seems like it doesn't make sense to add, it's probably worth closing.

I think most of the bugs that are still open are things I was never able to reproduce, so if we still aren't able to reproduce them, it's probably worth asking the original author about (and if they don't respond or don't have the issue anymore, we can probably just close it).

**Comment by dbfreem** [comment] 2019-05-30 02:54
I would definitly be on board with helping to clean up some. I could use the suggestions you made above in the process.

**Comment by PalmerAL** [comment] 2019-05-30 21:27
OK, great, thanks for doing this!

GitHub's permissions model is rather confusing, I've sent you an invitation to join the minbrowser organization, and I think once you accept that, I can [give you "triage" access to the repository](https://help.github.com/en/articles/managing-team-access-to-an-organization-repository), but I might end up having to redo this if I'm not understanding it correctly.

**Comment by dbfreem** [comment] 2019-05-30 22:42
Looks like I got the email and joined. I'll start looking at some of the items in a few days.

**Comment by PalmerAL** [comment] 2019-05-30 22:48
It turns out that I did have to add you to a team, but you should have access now, let me know if you don't.

**Closed** 2019-06-22 21:08 UTC

**Comment by PalmerAL** [comment] 2019-06-23 02:03
@dbfreem Thanks for spending so much time on this, it definitely does seem to be helping! (and there are more closed than open issues now, which I don't think has ever happened before).
