### ISSUE TITLE
Issue on https://discord.com/app

### ISSUE THREAD

**Issue by Ema-byte** [minbrowser/min#1441] opened 2021-01-17 19:36 UTC
![Capture](https://user-images.githubusercontent.com/77587251/104853800-83721d80-5903-11eb-9ec8-ca3372acf53f.PNG)
I can't click buttons on the part of the screen indicated with the blue pen. I've been experiencing this issue only on DISCORD for now. I'll update this `issue` whenever I find more.

**Comment by Milo123459** [comment] 2021-01-17 19:38
This is a known issue. Duplicate of #1381

**Closed by Milo123459** 2021-01-17 19:38 UTC
