### ISSUE TITLE
awkward navigation between tabs

### ISSUE THREAD

**Issue by erikivanmelo** [minbrowser/min#1415] opened 2021-01-02 21:44 UTC
When I have multiple tabs open, it's very uncomfortable to use "ctrl + tab" to navigate between them.

A possible solution is to add the classic "ctrl + number" or "alt + number" that the rest of the browsers have.

**Comment by Syndamia** [comment] 2021-01-04 07:48
Duplicate of #1239

**Closed by Syndamia** 2021-01-04 07:48 UTC
Labels: feature request, status/duplicate
