### ISSUE TITLE
Auto hide mode that hides the tab bar.

### ISSUE THREAD

**Issue by massiker** [minbrowser/min#1509] opened 2021-02-17 22:44 UTC
I think it would be great idea, since the idea of this browser is to be minimal to have a mode like that.
By turning it on in setting (and maybe have a hotkey for it), it will completely hide the UI (Tab bar in Min's case), and it would only reappear if: 
1) You hover over with the mouse where the invisible tab bar is
2) You use bindings that are related to the tab bar (such as switching tabs or entering urls, bookmarks, bangs etc.)

This may sound similar to fullscreen mode, but it really isn't.
It gives you more screen real estate even if the window is not maximized.

I hope you find this a good idea :)

**Comment by Syndamia** [comment] 2021-02-24 17:34
Duplicate of #1011. Also, it's better to make feature requests in the discussions tab.

**Closed by Syndamia** 2021-02-24 17:34 UTC
Labels: feature request
