### ISSUE TITLE
Bug: popups don't close

### ISSUE THREAD

**Issue by surajsharma** [minbrowser/min#143] opened 2016-05-12 05:06 UTC
Often times, the third-party login popups that are supposed to close and redirect to the original site do not close or redirect to the site, an example of where this can be seen in action is www.feedly.com i'm guessing this is a bug but it might not be.

**Comment by Smona** [comment] 2016-05-12 06:00
This sounds like the same issue as #140 and #142

**Comment by PalmerAL** [comment] 2019-07-29 22:11
Duplicate of #140

**Closed by PalmerAL** 2019-07-29 22:11 UTC
