### ISSUE TITLE
Can we get Chrome extensions, if this is based around Chromium?

### ISSUE THREAD

**Issue by whyhellobradley** [minbrowser/min#404] opened 2017-09-18 02:36 UTC
I'd be using Min permanently if there was a way to have extensions.

**Comment by PalmerAL** [comment] 2017-09-18 22:17
Min doesn't use the complete Chromium browser code, just the Chromium Content Module (through Electron). This means that we would have to reimplement the Chrome extension API's from scratch, which would be extremely difficult to implement and a huge burden to maintain. In the long term, if Min continues to grow in popularity and we have a group of people that are willing to invest the time to build and maintain these API's, I could see it happening, but for now it's not realistic to do. I'm going to close this is a duplicate of #1.

**Closed by PalmerAL** 2017-09-18 22:17 UTC
