### ISSUE TITLE
How to disable closing tabs on scroll?

### ISSUE THREAD

**Issue by dancojocaru2000** [minbrowser/min#1010] opened 2020-05-12 22:55 UTC
It's quite annoying as I already accidentally closed several tabs.

I also don't see a reopen closed tab menu or something.

**Comment by PalmerAL** [comment] 2020-05-13 20:09
Duplicate of #953.

Pressing shift+ctrl+t will re-open a closed tab; they should also show up near the top of the history list (and we should probably add a separate section for recently-closed to make sure they're always at the top).

**Closed by PalmerAL** 2020-05-13 20:09 UTC
