### ISSUE TITLE
Cursor control

### ISSUE THREAD

**Issue by ireallydontwantthisaccount** [minbrowser/min#741] opened 2019-05-11 00:32 UTC
The Min browser currently doesn't let websites control the cursor and it definitely should as it would support more games and other web apps that need to control the cursor.

**To reproduce:**
1. Go to [https://classic.minecraft.net/](https://classic.minecraft.net/)
2. Try to look around using the cursor, it shouldn't work

**Comment by PalmerAL** [comment] 2019-05-12 18:54
I think this is a duplicate of #332.

**Comment by ireallydontwantthisaccount** [comment] 2019-05-12 20:02
Ah, sorry, it is. Any ETA for this?

**Closed** 2019-05-12 20:05 UTC

**Comment by PalmerAL** [comment] 2019-05-13 00:15
I don't think there's a specific timeframe, I might do it at some point if I have time, or if you or someone else is interested in working on it you're welcome to do so.
