### ISSUE TITLE
Default browser little bug.

### ISSUE THREAD

**Issue by Vivinh0** [minbrowser/min#288] opened 2016-12-28 09:03 UTC
Min Browser version: 1.5.0-1 from https://aur.archlinux.org/packages/min-browser-bin
OS: Arch Linux.

The bug appear when you set Min Browser as your default browser. You have open the browser with some tabs then open a link from other app like your mail client, Telegram or a Twitter client,  Min Browser open this link in a new windows but with a copy of the tabs of the previous window.

Maybe this bug is solve in the last version. Awesome browser, congratulations.

**Comment by PalmerAL** [comment] 2016-12-28 22:27
This is a duplicate of #243.

**Closed by PalmerAL** 2016-12-28 22:27 UTC
