### ISSUE TITLE
show url when hover link

### ISSUE THREAD

**Issue by husnaram** [minbrowser/min#850] opened 2019-11-01 10:12 UTC
can the Min show url when my pointer over link?

thank you.

**Comment by PalmerAL** [comment] 2019-11-09 05:39
This isn't a built-in feature, but I wrote a userscript that you can install to do this: https://github.com/PalmerAL/min-link-tooltip-userscript.

The issue is a duplicate of #134.

**Closed by PalmerAL** 2019-11-09 05:39 UTC
