### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by Tomadelostacos** [minbrowser/min#757] opened 2019-05-22 10:41 UTC
Hello, is there something planned for the favicons in the tabs ?

**Comment by PalmerAL** [comment] 2019-05-23 01:16
Duplicate of #304.

In general, I think favicons would be kind of distracting, and it's also going to be difficult to find a way to do it that looks good, since tabs can have any possible color as their background (unless we wanted to remove that), but I can see how it would be nice to have a way to identify tabs more quickly. Maybe something where a portion of the tab uses the theme color for that page?

**Comment by Tomadelostacos** [comment] 2019-05-23 07:23
Yep, i personally identify my tabs with favicons in Opera, so that i instantly know in which website i'm gonna go when clicking, it's annoying (for me) if i have to read all labels beginnings when choosing a tab. 
Maybe having a little div at the left of every tab, a square with a dark grey background, hideable, could allow users to have favicons and to identify even more tabs ?

**Comment by PalmerAL** [comment] 2019-05-24 01:48
That's true, I guess if there was a background behind the favicon, it could be arranged in such a way that it never conflicts with the tab color.

This does seem like it would be useful in some situations, I guess I would be OK with adding an option to it.

**Comment by PalmerAL** [comment] 2019-05-24 01:48
Actually, we could probably detect what the colors in the favicon are, compare them to the background color, and only add the gray background if they're too similar to each other...

**Comment by Tomadelostacos** [comment] 2019-05-27 07:19
It could be a great idea, it's not "too heavy" if the user has a lot of opened tabs ?

**Comment by PalmerAL** [comment] 2019-05-30 21:30
It would probably make sense to hide the favicons if there are too many tabs open, although I'm not exactly sure what number that would be.

**Comment by Tomadelostacos** [comment] 2019-06-03 07:37
I personally don't fully agree on that. As a user, when i have a lot of tabs opened, i can find my tab faster with favicons + location in my tabs than with the first letters. (It's my personal opinion ! )

**Comment by PalmerAL** [comment] 2019-06-03 19:58
That's a good point, I guess an alternative would be to hide the title and just use the favicon when the tab reaches the minimum width.

**Comment by PalmerAL** [comment] 2020-07-31 04:00
Closing as duplicate of #304.

**Closed by PalmerAL** 2020-07-31 04:00 UTC
Labels: feature/preference, question
