### ISSUE TITLE
Question: Add spinner to tab when loading?

### ISSUE THREAD

**Issue by Andruj** [minbrowser/min#159] opened 2016-05-16 20:22 UTC
I have just started using this browser and have been very impressed. However, I was wondering how people felt about adding this feature. It would spin while the page is loading, similar to other browsers like Chrome.

**Comment by PalmerAL** [comment] 2016-05-16 21:17
This is a duplicate of #52. The designs discussed so far in that issue have all been progress bars, but a spinner would be an option too.

**Closed by PalmerAL** 2016-05-16 21:17 UTC
Labels: duplicate
