### ISSUE TITLE
Suggestion: Menu default in Linux...

### ISSUE THREAD

**Issue by baldrick-nz** [minbrowser/min#199] opened 2016-06-03 01:51 UTC
Whilst I think having the menu showing by default is excellent, I would also like a way of hiding it as well. 

Maybe start up with the menu visible, but keep the option of the 'alt' toggle, as prior to 1.3.1?

Love your work, keep it up!

**Comment by PalmerAL** [comment] 2016-06-03 14:22
This is a duplicate of #188.

**Closed by PalmerAL** 2016-06-03 14:22 UTC
