### ISSUE TITLE
Twitter login

### ISSUE THREAD

**Issue by sospedra** [minbrowser/min#144] opened 2016-05-12 14:44 UTC
For some reason I cannot log into Twitter. Maybe the no-tracking is being too aggressive?

**Comment by cakuki** [comment] 2016-05-13 09:48
Post request to `https://twitter.com/sessions` is blocked even "Block trackers and ads" option is disabled for me.

**Comment by simonhochrein** [comment] 2016-05-24 13:35
There should be a feature to whitelist domains from EasyList.

**Comment by PalmerAL** [comment] 2016-05-26 18:04
@simonhochrein Can you file a separate issue for that?

(That isn't related to this issue, since this issue occurs even when content blocking is disabled).

**Comment by simonhochrein** [comment] 2016-05-26 18:36
Oh sorry didn't notice that

**Comment by PalmerAL** [comment] 2017-11-12 01:36
I've added a workaround for this in b72721e12f8d025e186dc047efa48d8f94a7079f. Would you be willing to try the master branch and see if it works?

**Comment by PalmerAL** [comment] 2017-11-24 22:13
Closing as duplicate of #260.

**Closed by PalmerAL** 2017-11-24 22:13 UTC
