### ISSUE TITLE
tabs colors

### ISSUE THREAD

**Issue by akapitoha** [minbrowser/min#1315] opened 2020-11-05 16:07 UTC
**Can you describe the problem you're facing?**
hi,
very often I get confused on which tab is active, because in Min active tab has some kind of grey color, what usually mens inactive tab in other major browsers.
maybe you could consider some changes here. or an option to switch colors.
thank you

**Comment by Syndamia** [comment] 2020-11-05 17:42
Duplicate of #1047

**Closed by Syndamia** 2020-11-05 17:42 UTC
Labels: feature request, status/duplicate
