### ISSUE TITLE
Doesn't work with news website

### ISSUE THREAD

**Issue by kramer65** [minbrowser/min#375] opened 2017-07-04 14:38 UTC
The first website I tried gave me an error: `nrc.nl` gives an error while `www.nrc.nl` does work. I tried other websites from the Netherlands using only the domain (without www), but those do work. 

Any idea why this could be?

**Comment by PalmerAL** [comment] 2017-07-08 22:42
Odd, going to ```nrc.nl``` just redirects to ```www.nrc.nl``` for me. Is this using the latest version of Min (1.6.0)? Also, could you copy the error code you get? It should be in this part of the URL:

```
file:///path/to/min/app/pages/error/index.html?ec=<error code>&url=<url>
```

**Comment by PalmerAL** [comment] 2018-04-01 03:52
I can't reproduce this, so I'm going to close this issue. Feel free to reopen this if you have the problem again.

**Closed by PalmerAL** 2018-04-01 03:52 UTC

**Comment by kramer65** [comment] 2018-04-03 19:58
i just tried min again after about 9 months and it works a lot better now! This issue has been solved and I like it so much that I'll be testing it as my main browser in the coming days.. :-)
