### ISSUE TITLE
mindmup.com log in doesnot work

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1030] opened 2020-05-26 09:47 UTC
They have a weird way of loging in so i guess they will be only ones having such problem.

It opens a new tab where i log in to by google and then i am supposed to return to previous tab and be logged in, but it doesnot work. 

I would also be happy for a workaround, i have created few mindmaps on their website and i dont want to swith to other similar websites...

**Comment by PalmerAL** [comment] 2020-05-26 19:33
Duplicate of #140; there's a workaround listed in [this comment](https://github.com/minbrowser/min/issues/140#issuecomment-568231697) if you're willing to modify the Min source code, but it has some problems.

**Closed by PalmerAL** 2020-05-26 19:33 UTC
