### ISSUE TITLE
hoverng over links does not show the URL

### ISSUE THREAD

**Issue by steve-1776** [minbrowser/min#443] opened 2017-10-23 16:06 UTC
A tool in the safety arsenal, hovering over links should show the URL being linked to. Is there some way to preview a URL currently in Min before clicking on it?

**Comment by PalmerAL** [comment] 2017-10-23 21:58
Duplicate of #134. Currently, you can see the URL by right-clicking on it, but I agree that's not quite as convenient.

**Closed by PalmerAL** 2017-10-23 21:58 UTC
