### ISSUE TITLE
Menu Bar Contrast

### ISSUE THREAD

**Issue by adamlucax** [minbrowser/min#592] opened 2018-08-06 16:46 UTC
My top menu bar has no contrast with text, there are all white

![screenshot from 2018-08-06 13-40-48](https://user-images.githubusercontent.com/38107498/43729577-1b8b6776-997f-11e8-9513-ada565d3f294.png)

**Comment by PalmerAL** [comment] 2018-08-08 00:14
Duplicate of #519.

This is supposedly fixed in the most recent Electron version, so it should work correctly in 1.8 (which will probably be released in the next week or so).

**Closed by PalmerAL** 2018-08-08 00:14 UTC
