### ISSUE TITLE
Chrome Extensions Support 

### ISSUE THREAD

**Issue by JoaoNM** [minbrowser/min#1852] opened 2022-01-07 17:03 UTC
This would be an important feature to open up to more users: support chrome extensions! For example to support metamask and other web3 extensions would be a big advantage. There are a number of very useful extensions that people need to be able to install on their browser. Would be nice to see support for extensions on this browser.

**Comment by PalmerAL** [comment] 2022-01-09 05:44
Duplicate of #1. Tldr: a huge amount of work, so unlikely to happen.

**Closed by PalmerAL** 2022-01-09 05:44 UTC
Labels: feature request
