### ISSUE TITLE
Filename too long on Windows

### ISSUE THREAD

**Issue by alexsaesee** [minbrowser/min#61] opened 2016-04-18 09:08 UTC
Hi,

I extracted the Min-v1.1.2-win32-x64.zip on my computer and the copy end with errors with filenames too long in `node_modules` or `spdx-licences-ids`, `spdx-exceptions`, `stringify.js`.
- D:\Min[files here] = Error

**Edit** : After a step by step copy test, I see a lot of recursive `node_modules` in each directories. I'm not an engineer but the complete path to the deepest file is really... long with at least 5 `node_modules` dir recursively.

_System: Windows 10 Pro 64bit (Version 1511, OS version 10586.218)_

**Comment by TheInitializer** [comment] 2016-04-20 20:43
Duplicate of #47

**Comment by PalmerAL** [comment] 2017-11-11 23:38
This should be fixed now, since we're building with NPM 5, which doesn't do recursive directories any more.

**Closed by PalmerAL** 2017-11-11 23:38 UTC
