### ISSUE TITLE
Per site user css/javascript support

### ISSUE THREAD

**Issue by mikroskeem** [minbrowser/min#495] opened 2018-02-04 20:09 UTC
Example use would be to make sites dark and/or disable Slack's `https://slack-redir.net/link?url=...`

**Comment by PalmerAL** [comment] 2018-02-04 21:00
Duplicate of #117.

**Closed by PalmerAL** 2018-02-04 21:00 UTC

**Comment by mikroskeem** [comment] 2018-02-04 21:10
Whoops, didn't notice 😄

---- On Sun, 04 Feb 2018 21:00:35 +0000 notifications@github.com wrote ----

Duplicate of #117.
