### ISSUE TITLE
Attachment Download Problem

### ISSUE THREAD

**Issue by babycamel** [minbrowser/min#385] opened 2017-08-15 21:51 UTC
Grat browser. However, I've noticed a problem downloading attachments. E-mail attachments for example are not downloading properly, pdf's are downloading something that appears cached and MS-Office attachments are being locked on download. The same problem isn't arsiing with other other browsers, but appears to be specific to Min. I'm using a Mac.

**Comment by PalmerAL** [comment] 2017-08-18 21:11
I can reproduce the problem with the PDF viewer; not sure about the other two. Can you explain in more detail what is happening with emails and office files?

**Comment by PalmerAL** [comment] 2017-08-18 21:30
Temporary fix for the PDF viewer is in 1355fcec342c8ffa7a13ee1a94cd5caef70092a3; it should be included in 1.6.1 in the next couple of days. I plan to rewrite the PDF viewer eventually, but this should work for now.

**Comment by babycamel** [comment] 2017-08-18 21:37
Yes, when downloading word and xlsx documents it strips the file extension. I have found that I can rename the file adding the extension and I'm able to open it no problem. so the problem appears to relate to removing the extension alone and that this locks the file for reading.

**Comment by PalmerAL** [comment] 2017-08-18 22:04
OK, I can reproduce that as well. I think this is caused by electron/electron#10121. The suggestion in that issue to enable "show all filename extensions" in the Finder preferences worked for me, so you could try that as a workaround until this is fixed.

**Comment by babycamel** [comment] 2017-08-18 22:18
I just enabled the finder setting thanks for the tip. Will see how that
goes.

Research Website: rbeard.sdf.org
Github:  https://github.com/babycamel
Vitae: https://chroniclevitae.com/people/653618-rodney-beard
Orcid: http://orcid.org/0000-0001-5506-5424
Translator's Cafe:  https://rmbeard.TranslatorsCafe.com
Translation: http://www.sprachspiegel.com

**Comment by PalmerAL** [comment] 2017-09-08 21:45
This has been fixed in Electron, so it should be fixed in Min when we upgrade Electron in the next release.

**Comment by PalmerAL** [comment] 2017-09-29 00:32
This should be fixed in the latest version (1.6.3). You can download it from here: https://github.com/minbrowser/min/releases.

**Closed** 2020-07-14 20:56 UTC
