### ISSUE TITLE
Page magnification resets randomly on Windows

### ISSUE THREAD

**Issue by Majordomamutus** [minbrowser/min#371] opened 2017-06-19 14:11 UTC
As in title. After opening page (FB especially) and magnifying it to proper level it stays on this level for a while, and then resets to previous level. May be related to duble finger scrolling (sometimes d-f scrolling triggers reset). 
EDIT: Pages also don't keep the magnification after closing; PgDn also trigers reset.

**Comment by PalmerAL** [comment] 2017-06-21 21:41
I think you're correct that this is related to scrolling; scrolling with the ctrl key pressed will zoom in or out. We could possibly look into making this less sensitive.

**Comment by Majordomamutus** [comment] 2017-06-22 19:45
Thanks for reply :)
I've checked it double and here are the results: every type of scrolling resets page magnification, no matter it's d-f, down arrow, PgDn. It appears especially on FB page, but not only.
Browser also can't remember magnification of page and set same among tabs, I have to change it on every tab manually, it's quite annoying.

**Comment by PalmerAL** [comment] 2017-06-23 23:10
I can't reproduce the issue with scrolling on facebook - do you have a specific page where this happens? Also, what version of windows are you using?

> Browser also can't remember magnification of page and set same among tabs, I have to change it on every tab manually, it's quite annoying.

I've opened another issue for this: #372.

**Comment by Majordomamutus** [comment] 2017-06-25 13:41
Win 10 Creators Update
- youtube.com , after clicking notification bell, not connected to scrolling
- google.com serch results page, randomly, also after clicking on grafic results tab,
- scholar.google.pl results page, after clicking on "Od 2016" on left panel, not connected to scrolling
- czasgentlemanow.pl/2017/06/kiedy-przestrzegac-zasad/ after clicking in link and going back to this page magnification is reseted (nothing, when link is opened in new tab)
- facebook.com - it appears when loading new content eg. in newsfeed

**Comment by PalmerAL** [comment] 2017-06-25 22:37
The 2nd, 3rd and 4th issues are because zoom is reset whenever a new page is loaded, which I've added an issue for in #372.

Otherwise, I can't reproduce this. It looks like scrolling will only change the zoom if ```e.metaKey``` is true (https://github.com/minbrowser/min/blob/master/js/webview/swipeEvents.js#L72), which on windows is the windows key (and actually I think this code has a bug; this is supposed to be the ctrl key). Is there any way the windows key could be pressed when you are scrolling?

**Comment by Majordomamutus** [comment] 2017-06-29 10:09
No, it's not possible. Ctrl zooming works well. I think all this issue is #372.
PS I have no idea about code so far :D

**Comment by PalmerAL** [comment] 2017-06-30 20:34
OK, I'll close this and leave #372 open then.

**Closed by PalmerAL** 2017-06-30 20:34 UTC
