### ISSUE TITLE
separate preferences between Containers

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1036] opened 2020-05-29 16:47 UTC
so i intoduce you a new idea **Containers**

we have Tasks that are really nice, i love them so much. Lets say we also have a thing called containers and we have 2 of them, one named **Blue** and second named **Red**

 Inside of these containers we can add tasks, but none of the cookies will be shared. so it will be possible to log into same website with different accounts.

proxy servers could also be separated, so if we add proxy server to **Red** container it wont have effect on **Blue** container.

A lot of other things could be separated. I know this will require a lot of work, but i love the idea...
any thoughts on this?

**Comment by PalmerAL** [comment] 2020-05-29 21:01
Duplicate of #634 I think.

If we did end up doing this, I think it would make more sense to have the separation be per-tab rather than per-task (like Firefox's container feature); if you open a new tab, we could ask whether you want to use the same container as the last tab or not.

**Comment by shalva97** [comment] 2020-05-29 23:08
yeah, it is duplicate of that....

Firefox's containers where good but too simple, when i saw it from that day idreamed for it to become more than just separating cookies...Anyways, your idea is good, however asking about whcih container to open seems annoying, a right click to manualy choose a container will be better.... 

I dont want to copy Firefox but i guess it seems to be best way...

**Comment by PalmerAL** [comment] 2020-05-30 02:09
What other things would you want to be separated? I know you mentioned proxy servers, but I don't think we have a setting for that anyway.

**Comment by shalva97** [comment] 2020-05-30 15:46
i dont think there is much else to separate... Maybe user agent? 

There could be something like **Private Container** where history wont be saved and cache will be ignored...

In the far future if Min gets extension support we could also separate them. Sometimes i am too anxious for them to run in the background always...

**Comment by Sestowner** [comment] 2020-07-23 13:57
Duplicate of #634.

**Closed by Sestowner** 2020-07-23 13:57 UTC
