### ISSUE TITLE
Incorrect file owners and groups in `/usr/lib` after installing `.deb` package

### ISSUE THREAD

**Issue by will-ca** [minbrowser/min#824] opened 2019-09-09 21:58 UTC
Installing Min using the below link through the most straightforward (`xdg-open`/`gdebi-gtk`) method created a file hierarchy with incorrect permissions, owners, and groups.

Installed link: https://github.com/minbrowser/min/releases/download/v1.11.0/min_1.11.0_amd64.deb

```
computer@computer:~
$ uname -a
Linux computer 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux

computer@computer:~
$ apt-cache show min
Package: min
Status: install ok installed
Priority: optional
Section: web
Installed-Size: 182420
Maintainer: Min Developers <280953907a@zoho.com>
Architecture: amd64
Version: 1.11.0-1
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libuuid1, kde-cli-tools | kde-runtime | trash-cli | libglib2.0-bin | gvfs-bin, gconf2, gconf-service, gvfs-bin, libasound2, libc6, libcap2, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, python
Recommends: pulseaudio | libasound2
Suggests: gir1.2-gnomekeyring-1.0, libgnome-keyring0, lsb-release
Description: Min is a fast, minimal browser that protects your privacy.
 A web browser with smarter search, improved tab management, and built-in ad 
 blocking. Includes full-text history search, instant answers from DuckDuckGo, 
 the ability to split tabs into groups, and more.
Description-md5: dbc967870819f6700852428a440dbec1
Homepage: https://minbrowser.github.io/min/

computer@computer:~
$ min
[6740:0909/225218.825378:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/min/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

computer@computer:~
$ ls -l /usr/lib | grep min
drwxr-xr-x  5  501 staff    4096 Sep  9 22:41 min

computer@computer:~
$ ls -l /usr/lib/min
total 148560
-rw-r--r-- 1 501 staff    145945 Aug 18 03:31 chrome_100_percent.pak
-rw-r--r-- 1 501 staff    209147 Aug 18 03:31 chrome_200_percent.pak
-rwxr-xr-x 1 501 staff   5099032 Aug 18 03:31 chrome-sandbox
-rw-r--r-- 1 501 staff  10410272 Aug 18 03:31 icudtl.dat
-rwxr-xr-x 1 501 staff    252168 Aug 18 03:31 libEGL.so
-rwxr-xr-x 1 501 staff   2936656 Aug 18 03:31 libffmpeg.so
-rwxr-xr-x 1 501 staff   7071360 Aug 18 03:31 libGLESv2.so
-rw-r--r-- 1 501 staff   3961766 Aug 18 03:31 LICENSES.chromium.html
drwxr-xr-x 2 501 staff      4096 Sep  9 22:41 locales
-rwxr-xr-x 1 501 staff 112456472 Aug 18 03:31 min
-rw-r--r-- 1 501 staff     83237 Aug 18 03:31 natives_blob.bin
drwxr-xr-x 3 501 staff      4096 Sep  9 22:41 resources
-rw-r--r-- 1 501 staff   8471330 Aug 18 03:31 resources.pak
-rw-r--r-- 1 501 staff    279704 Aug 18 03:31 snapshot_blob.bin
drwxr-xr-x 2 501 staff      4096 Sep  9 22:41 swiftshader
-rw-r--r-- 1 501 staff    702384 Aug 18 03:31 v8_context_snapshot.bin
-rw-r--r-- 1 501 staff         5 Aug 18 03:31 version
```

**Comment by PalmerAL** [comment] 2019-09-10 02:01
Duplicate of #778. It looks like it should be really easy to fix this, I'm not sure why I didn't before. But it should be fixed for the next release.

In the meantime, you should be able to manually change the permissions on the helper to get it to work, or you can also run `min --no-sandbox`.

**Closed by PalmerAL** 2019-09-10 02:01 UTC

**Comment by PalmerAL** [comment] 2019-09-17 23:07
I think this should be fixed in the latest release: https://github.com/minbrowser/min/releases/tag/v1.11.1, let me know if you're still having trouble with it.
