### ISSUE TITLE
Can't login to Gmail 

### ISSUE THREAD

**Issue by vudoanbinhminh** [minbrowser/min#1123] opened 2020-07-11 16:49 UTC
![image](https://user-images.githubusercontent.com/33306530/87229266-ef158400-c3d0-11ea-8e19-40849e052d52.png)

It's say
"Could not log in for you
This browser or application may not be secure. looking for more information

Please try using another browser. If you are using a supported browser, you can refresh the screen and try logging in again."

what I have to do  ?

![image](https://user-images.githubusercontent.com/33306530/87229287-1a986e80-c3d1-11ea-9ac8-6f062183bbe0.png)

**Comment by PalmerAL** [comment] 2020-07-11 16:59
Open the Min preferences, enable “use a custom user agent”, and enter the value in this comment: https://github.com/minbrowser/min/issues/868#issuecomment-650825871

**Comment by Syndamia** [comment] 2020-07-26 06:38
Duplicate of #868 and the OP has liked the provided solution (meaning it worked).

**Closed by Syndamia** 2020-07-26 06:38 UTC
Labels: status/duplicate
