### ISSUE TITLE
Blank pages in Ubuntu 16.04 for 4k resolution

### ISSUE THREAD

**Issue by darwinrc** [minbrowser/min#223] opened 2016-07-29 20:12 UTC
Copied from the same issue in Brave browser: 
"I'm continuously experiencing blank page problem on Linux Ubuntu. I'm not sure how would you reproduce the problem. It just shows blank. May try the following steps:

Open any site
Let go the browser, minimize and wait few minutes (I'm not sure if this is needed)
Maximize, open new tab, try visiting any site
Blank page!! afterwards.
Now you won't be able see any new tabs page contents except the initial ones."

This could be a hint: I tested another Electron-based browser (Brave) in the same machine (Ubuntu 16.04 x86_64) and got the same results. When in 1920x1080 it works fine, but in 3840x2160 I got blank pages after a few opened tabs.

**Comment by PalmerAL** [comment] 2016-07-30 01:54
Since this also occurs in Brave, it's probably an Electron issue, you might want to report this issue there.

**Comment by PalmerAL** [comment] 2019-10-12 16:58
Since no one else has been able to reproduce this, I'm going to close this issue.

**Closed by PalmerAL** 2019-10-12 16:58 UTC
Labels: Linux, bug
