### ISSUE TITLE
Web browsing data

### ISSUE THREAD

**Issue by kalvinator** [minbrowser/min#740] opened 2019-05-03 14:39 UTC
Interesting web browser but it's too minimalist. There is no way to delete your web browsing data, cookies or pop up tab link address... 

Also, unfortunately it does not accept extension...

**Comment by PalmerAL** [comment] 2019-05-03 21:41
You can delete your history with the `!clearhistory` command; starting in the next release, you will also be able to delete individual items from the history view.

You're right we should add a way to delete cookies; I think we could probably make this part of the `!clearhistory` command as well. In the meantime, if you just want to remove cookies for a specific site, there's a somewhat hidden option to do so: developer menu > inspect page > application tab > clear site data.

Can you clarify what you mean by "pop up tab link address"?

Extension support is quite difficult unfortunately, I don't see that happening anytime soon (although there has been some work to add support to Electron, which would make it easier to implement).

**Comment by dbfreem** [comment] 2019-06-28 21:17
Cookies are a duplicate of #306

**Closed by dbfreem** 2019-06-28 21:17 UTC

**Comment by BenTearzz** [comment] 2019-07-12 21:18
@PalmerAL about extensions, couldn't you guys make an easy system as "load plugin / extension" which is just a user-script and then place / copy the contents of the script to the right folder.

So that, the user doesn't have to go digging around in directories, but can just, "load it".
Of course, if user-scripts aren't enabled, this should probably trigger a confirmation message saying, "This could be unsafe!" or whatever.

**Comment by PalmerAL** [comment] 2019-07-13 04:28
@BenTearzz Do you mean like a button on the settings page to import a userscript? Or do you mean that userscripts should also be able to modify the browser UI, and be an extension replacement?

Either way, a new issue would be good!
