### ISSUE TITLE
Webservices login through google

### ISSUE THREAD

**Issue by TheoOliveira** [minbrowser/min#377] opened 2017-07-05 11:37 UTC
I didn't test with other services but it I used feedly.com and hootsuite.com as well. The 1st keeps loading the google login and does nothing. In feedly it connects but the login page doesn't close and if a refresh it shows  the disconnected page again.

**Comment by PalmerAL** [comment] 2017-07-08 22:46
I think this is because Min doesn't support popup windows: #140.

**Comment by dbfreem** [comment] 2019-08-04 01:03
duplicate of #140

**Closed by dbfreem** 2019-08-04 01:03 UTC
