### ISSUE TITLE
Password manager?

### ISSUE THREAD

**Issue by kodaxx** [minbrowser/min#521] opened 2018-03-24 01:29 UTC
I love MIn. It is almost enough to actually replace my main browser...I just need some kind of minimal password manager. Is this a plan?

**Comment by PalmerAL** [comment] 2018-03-24 01:58
Duplicate of #391.

I've avoided doing this, mostly because I think it would be pretty difficult to ensure that it is secure, but if enough people want it I guess we could do it.

**Closed by PalmerAL** 2018-03-24 01:58 UTC

**Comment by PalmerAL** [comment] 2019-02-06 00:00
@djakabok That would require adding support for the Chrome extension API's, which is a pretty huge undertaking, but we might consider it at some point in the future.

**Comment by PalmerAL** [comment] 2019-02-07 05:57
@djakabok They implemented support for a subset of the Chrome extensions API to do that, see this PR for example: https://github.com/brave/browser-laptop/pull/3867. We could theoretically do the same thing, but it' s a massive amount of work, and adds a lot of complexity to the codebase that makes it harder to make changes in the future. Maybe at some point in the future, if we can build a larger community of people contributing to Min, this would be possible, but I don't see it happening any time soon.
