### ISSUE TITLE
Clicking links opens new min window

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#576] opened 2018-07-01 07:56 UTC
Under Debian clicking on a URL Link (from outside of min, for instance on a PDF file ....) will open a new window. How can i setup min to open new links as a new tab?

thanks

**Comment by PalmerAL** [comment] 2018-07-07 03:32
I think this is a duplicate of #243?

**Comment by ateymuri** [comment] 2018-07-07 10:54
It doesn't seem to be solved there?

**Comment by PalmerAL** [comment] 2018-07-07 22:16
@ateymuri It isn't fixed yet, but if both of these issues are about the same thing, it's easier to just leave one of them open.

**Comment by dbfreem** [comment] 2019-06-22 20:49
duplicate of #243

**Closed by dbfreem** 2019-06-22 20:49 UTC
