### ISSUE TITLE
Open files image preview working in Chrome but not Min

### ISSUE THREAD

**Issue by orschiro** [minbrowser/min#279] opened 2016-11-28 14:37 UTC
# Chrome
![image](https://cloud.githubusercontent.com/assets/170947/20672149/7f4f7a0c-b580-11e6-9d9f-984d1e39760d.png)

# Min
![image](https://cloud.githubusercontent.com/assets/170947/20672173/9110ad6a-b580-11e6-9f4b-8880598f2a85.png)

**Comment by Sestowner** [comment] 2020-07-22 13:57
I can't reproduce this, so I'm going to close this issue. Feel free to reopen this if you have the problem again.

**Closed by Sestowner** 2020-07-22 13:57 UTC
