### ISSUE TITLE
change mouse wheel action when hovering over tabs

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1133] opened 2020-07-15 15:43 UTC
if i hover my mouse on tabs and scroll it will show Tasks list. I guess this is okay but, scroll bar shows up if there are about 10 tabs open, so it should be intuitive that a mouse wheel should scroll tabs and otherwise do nothing....

what do you think?

**Comment by PalmerAL** [comment] 2020-07-20 03:21
Duplicate of #953.

**Closed by PalmerAL** 2020-07-20 03:21 UTC
