### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by mj162** [minbrowser/min#1730] opened 2021-09-04 21:09 UTC
Developers,

Thank you for developing and maintaining the Min Browser.  I am new to Min -- like 'discovered' it 20 mins ago.  Why was I looking?  I have 'installed' (see below) Brave, Tor, Vivaldi and Waterfox and, not 100% satisfied with all, did the usual web search (again) for non-spammy browsers for Linux and came-across Min.

Without stating the obvious to those that have clearly already come-across Min, when you go to the bottom of the landing page of most of the others to try to discover who is behind them, it can be a little opaque and when set against the default behaviour of their browsers when you first try them, you wonder the 'good guy' guise isn't subterfuge.  I like what I see so far, so thank you.

ObAppImage: Environment: HP ThinClient running HP ThinPro 7.1 (OEM Ubuntu 16.04 LTS) and HP ThinPro 18.04 (OEM Ubuntu 18.04 LTS).  Running the installer would invalidate HP service contract.  All added apps are run 'portably' off of an NFS share or local BTRFS USB stick.  If Min turns-out to be a favoured one that's installed and updated frequently, possibly replacing one of the others, it would greatly simplify (and greatly increase the chances of adoption) if Min was also (or instead of) published as a distro-agnostic AppImage.  (Snap and Flatpak require helpers that aren't included in HP's OS and we can't add or change OS components, so only AppImage is an option for us).  Waterfox is published nightly as an AppImage.

Thank you.

**Comment by maverick74** [comment] 2023-01-04 12:22
dupe of #567

**Comment by Kepler-69c** [comment] 2024-02-03 10:29
Close issue because it is a duplicate

**Closed by Kepler-69c** 2024-02-03 10:29 UTC
