### ISSUE TITLE
Bug on Menu Bar

### ISSUE THREAD

**Issue by italo-rp** [minbrowser/min#545] opened 2018-04-10 18:39 UTC
Hello guys, i use ZorinOS now, and i started to use MinBrowser right now, and i realize that the Menu Bar to access preferences and stuffs like the "About min" is completly white, there's no letters there. 

This 'white space' between the window Min and the windows of min like the github it's in blank, althougt it's working without problem. 
![captura de tela de 2018-04-10 15-34-55](https://user-images.githubusercontent.com/37498452/38576649-1be8b040-3cd5-11e8-9191-8c7bdb3f21ee.png)

**Comment by PalmerAL** [comment] 2018-04-10 22:30
Duplicate of #519. This is apparently fixed in the latest version of Electron, so it should be fixed in the next release. In the meantime, you can  build it yourself: https://github.com/minbrowser/min#developing. To use the latest version of Electron, you'll have to change ```electronVersion``` in package.json to "2.0.0-beta.7".

**Closed by PalmerAL** 2018-04-10 22:30 UTC

**Comment by PalmerAL** [comment] 2018-06-28 15:58
Not as far as I know. If you wanted, you could change "electronversion" in package.json to a later version (probably 2.0.3 would work best) and follow the instructions in the readme to build a new binary. Otherwise, I'm hoping to release 1.8 soon, although there are a couple of bugs in Electron 3 that need to be fixed first.
