### ISSUE TITLE
"Open in new tab" doesn't function in developer tools

### ISSUE THREAD

**Issue by clayton-grey** [minbrowser/min#1388] opened 2020-12-17 04:30 UTC
- 1.17.1
- macOS 10.14.6

## Expected Behavior

Clicking "Open in New Tab" in the developer panel should open the resource in a new tab within the same task.

## Actual Behavior

No new tab is opened.

## To Reproduce

Right click a link within the developer tools and select "Open in new tab".

**Comment by PalmerAL** [comment] 2020-12-21 00:21
Duplicate of #1034.

**Closed by PalmerAL** 2020-12-21 00:21 UTC
Labels: bug
