### ISSUE TITLE
Video Not playing - Dazn

### ISSUE THREAD

**Issue by lelliott79** [minbrowser/min#1365] opened 2020-11-29 17:47 UTC
Any way we can get video to work with services such as DAZN?

**Comment by PalmerAL** [comment] 2020-11-29 23:47
Playing DRM video (which I think DAZN is included in) requires from a license from Google, which they won't provide to anyone. So this unfortunately isn't possible.

Duplicate of #641.

**Closed by PalmerAL** 2020-11-29 23:47 UTC
