### ISSUE TITLE
Minimize Button

### ISSUE THREAD

**Issue by mtgperales** [minbrowser/min#1118] opened 2020-07-08 11:30 UTC
I don't know if this problem exists only in my computer but every time i click the minimize button on the upper right, it just does not work. It will show the desktop for like 0.1 seconds and return back to the browser

Min version: v1.15.0
Installed from Arch official repository

**Comment by Sestowner** [comment] 2020-07-08 17:30
Duplicate of #1074.

**Closed by Sestowner** 2020-07-08 17:30 UTC
