### ISSUE TITLE
Ctrl+Left and Ctrl+Right navigating instead of moving cursor

### ISSUE THREAD

**Issue by whitelynx** [minbrowser/min#41] opened 2016-04-15 15:17 UTC
When typing, I constantly use Ctrl+Left to move one word to the left, and Ctrl+Right to move one word to the right -- something generally implemented at the OS or GUI toolkit level, and supported on most platforms I've used. On Linux, pressing those keys in Min causes it to navigate back and forward instead of moving the cursor, unlike all other apps on the system.

**Comment by PalmerAL** [comment] 2016-04-15 21:25
It looks like Firefox only navigates back or forward if there is not a text field focused. Min should probably do the same.

**Comment by topher1kenobe** [comment] 2016-05-13 18:08
Also in Linux, many window managers use ctrl-left/right to change virtual desktops.  Like mine. So I can't go forward and back at all. Firefox uses alt-left/right, that would be magnificent.

**Comment by airdrik** [comment] 2016-07-29 21:21
This caught me by surprise as I was writing up a comment somewhere and tried to use Ctrl+Right to move the cursor over a word (which I use quite frequently in pretty much every text field) and instead of moving the cursor, it went back a page (or two or more, I don't remember for sure) and I lost the comment I was writing up.
I believe that alt+left/right is pretty common among browsers for back/forward, while ctrl+left/right is common among text elements for move one word left/right.  
(from the looks of the keyboard settings, it looks like it was designed for Mac and then patched to PC by just replacing cmd with ctrl; but unfortunately reality is a little more complicated than that)

**Comment by PalmerAL** [comment] 2016-07-30 01:58
As a workaround for this issue, you can open the preferences, and delete the text in the "Go Back" field under "Keyboard Shortcuts".

**Comment by PalmerAL** [comment] 2017-11-10 06:27
This was fixed in 1.6.0.

**Closed by PalmerAL** 2017-11-10 06:27 UTC
Labels: bug
