### ISSUE TITLE
how to block ads on youtube

### ISSUE THREAD

**Issue by annihilation666** [minbrowser/min#1889] opened 2022-01-26 01:49 UTC
I found this script on github that increases the speed of ads. It is not the same as removing them but it does its job.
https://github.com/GSRHackZ/No-ADS-YouTube

instructions: just search how to install userscripts in min :D

sry for my english btw

**Comment by annihilation666** [comment] 2022-01-26 04:02
!run no ads 
and f5

**Comment by voxrie** [comment] 2022-05-03 18:46
interfere with the userjs and add the following to its content

// @run-at       document-start

![resim](https://user-images.githubusercontent.com/64368231/166521520-a9c150ce-07c0-4989-a442-38990e6cee30.png)

**Comment by Kepler-69c** [comment] 2024-02-03 19:34
(duplicate of #1121)

Min's built-in adblocker currently doesn't work reliably on YouTube. To block ads on youtube, you can try [this userscript](https://github.com/minbrowser/min/issues/1121#issuecomment-663021909) or [this one](https://github.com/alisanoelia/yt-block) instead.

How to use user scripts is explained on the [Min GitHub wiki](https://github.com/minbrowser/min/wiki/userscripts).

Feel free to ask if you still have problems!

**Closed by Kepler-69c** 2024-02-03 19:34 UTC
Labels: status/duplicate, bug/content-blocking
