### ISSUE TITLE
A page forward 'button' to go with the page back one

### ISSUE THREAD

**Issue by ep1955** [minbrowser/min#1216] opened 2020-08-27 02:29 UTC
**Can you describe the problem you're facing?**
I really like Min but I've never understood why there is no page forward button to go with the page back one.  This is a feature in probably every other browser I've seen/used... it just makes sense to have one and would be very handy.

**What solution would you like?**

A page forward button.

**Are there any alternatives you've considered?**

Key bindings work well but if you already have a number of them it can be a bit of a trick to setup good ones for the page forward/back functions, plus given that web browsing tends to be mouse-centric your hand is more than likely on the mouse anyway.  Please give this some consideration, thanks!

**Comment by Sestowner** [comment] 2020-08-27 07:50
Duplicate of #744.

**Closed by Sestowner** 2020-08-27 07:50 UTC
Labels: feature request
