### ISSUE TITLE
Finder access when downloading a file

### ISSUE THREAD

**Issue by M-Arnone** [minbrowser/min#2322] opened 2023-09-26 07:36 UTC
- **Min Version:**
1.29.0

- **Operating system:**
ventura 13.5.2

## Expected Behavior
Display the file in the repo where it is

## Actual Behavior
Button crashes Finder app

## To Reproduce
1. Download a file
2. Click on this button (view picture)
<img width="318" alt="SCR-20230926-iwgr" src="https://github.com/minbrowser/min/assets/56111638/0a32a760-4dde-4405-bfa8-683d84ad2aed">

**Comment by iambudi** [comment] 2023-09-30 11:18
On MacOS Sonoma, i could not even see the whole download bar in the bottom.
Should we add an additioanal menu to show the download history?

**Comment by M-Arnone** [comment] 2023-10-01 08:14
> On MacOS Sonoma, i could not even see the whole download bar in the bottom. Should we add an additioanal menu to show the download history?

Why not but first, let's fix for those who sees the download. 
I downloaded Sonoma but get back to Ventura, Sonoma is too bugged this day.

**Comment by PalmerAL** [comment] 2023-10-05 02:46
Fixed in 1180df5690488608e179d0a6380c408a77f06416, thanks for reporting.

@iambudi Can you add a screenshot in a new issue?

**Closed** 2023-10-05 02:45 UTC
Labels: bug

**Comment by M-Arnone** [comment] 2023-10-05 10:05
How to download the version with the bug fixed ?

**Comment by PalmerAL** [comment] 2023-10-05 18:55
@M-Arnone You can either wait for the next published release, or build it yourself: https://github.com/minbrowser/min#building-binaries

**Comment by iambudi** [comment] 2023-10-06 00:08
> @M-Arnone You can either wait for the next published release, or build it yourself: https://github.com/minbrowser/min#building-binaries

I tried to run `npm run start` on node v20.8.0 and show this error popup.
![image](https://github.com/minbrowser/min/assets/31809529/fc34c552-de9a-43be-aa14-409bc0c8330d)

`npm install readable-stream` seems does not help

**Comment by iambudi** [comment] 2023-10-14 01:34
> Fixed in [1180df5](https://github.com/minbrowser/min/commit/1180df5690488608e179d0a6380c408a77f06416), thanks for reporting.
> 
> @iambudi Can you add a screenshot in a new issue?

#2330

**Comment by PalmerAL** [comment] 2023-10-19 05:23
@iambudi I can't reproduce this; maybe try deleting your whole node_modules folder and reinstalling?
