### ISSUE TITLE
Enhancement Request: Back Button

### ISSUE THREAD

**Issue by mokane99** [minbrowser/min#212] opened 2016-07-10 16:29 UTC
There really needs to be a back button somewhere so that you can retrace steps. Yes, you can use the keyboard (mod+left cursor) but if you're using a mouse or trackpad your hands aren't on the keyboard.

**Comment by PalmerAL** [comment] 2016-07-10 17:16
Duplicate of #85.

**Closed by PalmerAL** 2016-07-10 17:16 UTC
