### ISSUE TITLE
Adding Shortcut keys similiar to vim keys

### ISSUE THREAD

**Issue by tsjazil** [minbrowser/min#1759] opened 2021-10-04 12:01 UTC
Adding bindkeys similar to vim keys will be helpful  

And also Better to make in dark every were in dark mode

**Comment by Syndamia** [comment] 2021-10-08 04:45
You can already do that with a [userscript](https://github.com/minbrowser/min/wiki/userscripts): [PalmerAL/min-vim-mode](https://github.com/PalmerAL/min-vim-mode). Also, duplicate of #37.

**Closed by Syndamia** 2021-10-08 04:45 UTC
Labels: feature request
