### ISSUE TITLE
Double-vision when scrolling

### ISSUE THREAD

**Issue by MarkWahlsten** [minbrowser/min#250] opened 2016-09-09 07:55 UTC
Hello,

The content of the page appears to double-up when scrolling. Here's a gif illustrating what I mean:
[https://gyazo.com/3c6f403eda435c9da3f4e0495d56cbb2](url)

I am using:
Min version 1.4.1, on OSX Yosemite 10.10.5

It appears to happen consistently on certain pages/websites, as well as in Min preferences, but on some sites it does not. 

Version 1.2.2 didn't have this issue, I first encountered it when I upgraded to 1.3.1.

**Comment by dungvu-qe** [comment] 2016-09-09 10:20
same issue 👍

**Comment by PalmerAL** [comment] 2016-09-11 21:54
I've also seen this occasionally, although I can't reproduce it with the preferences.

This looks like a Chromium issue, so it's possible upgrading to the latest version of Electron will fix this.

**Comment by PalmerAL** [comment] 2016-10-01 01:42
Still happening in Chromium 53.

**Comment by dlanznar** [comment] 2016-12-16 16:39
I think I am seeing this as well (1.5.1 on 10.10.5) but the gif is 404.  Attached a screenshot.
![screen shot 2016-12-16 at 11 34 58 am](https://cloud.githubusercontent.com/assets/113007/21270309/140e93b0-c384-11e6-9a89-60eba6863389.jpg)

**Comment by PalmerAL** [comment] 2016-12-17 03:03
Can you reproduce this consistently? I've seen this before as well, but it happens so rarely that it's hard to debug.

**Comment by dlanznar** [comment] 2016-12-17 03:36
Yes, I can make it happen fairly easily, though sometimes it does take a few tries. 

I start it up and go to https://minbrowser.github.io/min/ <https://minbrowser.github.io/min/> (which is the startup URL), and scroll the page up and down repeatedly,  and after a few times, usually, it 
occurs.

**Comment by PalmerAL** [comment] 2016-12-28 23:20
I think this is fixed in the ```scrolling``` branch. Could you please try that branch and see if it works?

I can only reproduce this consistently by scrolling while the searchbar is open, so I'm not sure if I'm seeing the same issue or not.

**Comment by dlanznar** [comment] 2016-12-29 03:23
Actually, I have updated my OS to SIerra now, and I no longer see the behavior in Min.   Sorry I can’t help!

**Comment by PalmerAL** [comment] 2017-09-03 18:17
Does anyone still have this issue?

**Comment by MarkWahlsten** [comment] 2017-09-04 04:49
Hi @PalmerAL, I haven't been having this issue since updating to Sierra

**Comment by PalmerAL** [comment] 2017-09-06 22:15
OK, I'm going to close this issue since nobody seems to be experiencing problems anymore. If you have this problem again, feel free to re-open this or create a new issue.

**Closed by PalmerAL** 2017-09-06 22:15 UTC
Labels: bug
