### ISSUE TITLE
Webcam is not working

### ISSUE THREAD

**Issue by birobirobiro** [minbrowser/min#2226] opened 2023-04-22 20:58 UTC
- **Min Version: 1.27.0**
- **Operating system: macOS 13.3.1**

## Expected Behavior
Webcam works

## Actual Behavior
![image](https://user-images.githubusercontent.com/22185823/233805743-e97c31e3-f50f-4635-b296-66a47584b907.png)

## To Reproduce
- Access this site: https://webcam-capture-beta.vercel.app/
- Select the desired webcam in the input

**Comment by Oleksandr0118** [comment] 2023-04-28 07:56
The same problem, the microphone and camera do not work in the newest version, download the previous version 1.26.0

**Comment by anhood** [comment] 2024-01-27 17:11
See ticket 1874
https://github.com/minbrowser/min/issues/1874

**Comment by Kepler-69c** [comment] 2024-04-27 19:36
closed as a duplicate of #1874

**Closed by Kepler-69c** 2024-04-27 19:36 UTC
Labels: bug, status/duplicate
