### ISSUE TITLE
1.29.0 installation errors

### ISSUE THREAD

**Issue by alex-yte** [minbrowser/min#2341] opened 2023-11-05 19:34 UTC
- **Min Version:**
1.29.0
- **Operating system:**
Ubuntu 23.10

## Expected Behavior
I expect it to install completely with no errors or broken dependencies
## Actual Behavior

After installation it gives me an array of problems reports

dpkg: dependency problems prevent configuration of min:
 min depends on gconf2; however:
  Package gconf2 is not installed.
 min depends on gconf-service; however:
  Package gconf-service is not installed.

dpkg: error processing package min (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 min

And those errors prevent me to install anything else. 
Every time i need to install something i have to sudo apt --fix-broken install which removes min and then reinstall it.

Apparently, there is some problem with gnome 2 configs which are not really supported in the gnome45.

**Comment by alex-yte** [comment] 2023-11-06 21:44
https://2h3ph3rd.medium.com/how-to-install-libgconf-2-4-on-ubuntu-23-10-fec6bda8d5f5

This article helped to solve the issue.
But, I believe, the solution is not very stable

**Comment by PalmerAL** [comment] 2023-11-07 03:23
Sorry about that, this is a duplicate of #2324 and will be fixed in the next release.

**Closed by PalmerAL** 2023-11-07 03:23 UTC
Labels: bug
