### ISSUE TITLE
Can't login to sites by Google or Facebook

### ISSUE THREAD

**Issue by Whii** [minbrowser/min#573] opened 2018-06-22 16:34 UTC
Both said "Session doesn't exist" or something like that.
Also, this website (http://notify.moe) doesn't load correctly on this browser I guess.

**Comment by abrarShariar** [comment] 2018-08-26 17:46
hey @Whii the site is loading like this for me: 

 ![Imgur](https://i.imgur.com/5XLhz6B.png)

Can you please mention your system spec?

**Comment by lordhellraiser** [comment] 2018-11-02 04:52
[Feedly](https://feedly.com) with Google doesn't seem to work with Min 1.8 (W10 x64)

**Comment by dbfreem** [comment] 2019-06-22 21:11
@whii and @lordhellraiser can you comment if this is still an issue for you. If so what OS are you on?

**Comment by PalmerAL** [comment] 2019-06-23 02:00
@dbfreem The login issues are because popup window support is missing, which is a duplicate of #140 (or one of a bunch of other issues open about this).

I can't reproduce the second issue, maybe it was a temporary thing?

**Comment by dbfreem** [comment] 2019-07-14 01:20
duplicate of #140

**Closed by dbfreem** 2019-07-14 01:20 UTC
