### ISSUE TITLE
[Feature Request] Using Chrome Extensions?

### ISSUE THREAD

**Issue by BKenzie7** [minbrowser/min#956] opened 2020-04-03 09:45 UTC
Is there any way to allow the use of Chrome Extensions? Any code that can be done to allow this?

**Comment by PalmerAL** [comment] 2020-04-04 03:22
Unfortunately, this is fairly complicated, and would require a lot of work to implement, but it may be done someday.

Duplicate of #1.

Depending on the extension, we could also consider having built-in functionality to replace it, or it might be possible to replace it with a [userscript](https://github.com/minbrowser/min/wiki/userscripts) - which extensions do you want to use?

**Comment by BKenzie7** [comment] 2020-04-10 12:49
I want to use a custom extension that is designed for web security in the same way Web Of Trust (WOT) is

**Comment by PalmerAL** [comment] 2020-04-12 04:43
OK, that's probably not something we'll implement, but you might be able to do it with a userscript. Since there's already an issue for full extensions support, I'm going to close this.

**Closed by PalmerAL** 2020-04-12 04:43 UTC
