### ISSUE TITLE
when unmaximizing video menu bar appears

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1459] opened 2021-01-24 18:33 UTC
- **Min Version:** KDE
- **Operating system:** 1.17.3

## Expected Behavior
it shouldnot appear

## Actual Behavior
If I have enabled "show separate title bar" and unmaximize youtube video manu bar shows up. Also dont mind that title bar is missing, it is disabled from KDE.
![image](https://user-images.githubusercontent.com/22417494/105639850-df085200-5e93-11eb-91f5-1e8c874ee1d0.png)

## To Reproduce
have  "show separate title bar" enabled and try to minimize/maximize youtube video. Sometimes it will disappear by itself

**Comment by Sestowner** [comment] 2021-01-26 13:01
Duplicate of #952.

**Closed by Sestowner** 2021-01-26 13:01 UTC
Labels: bug
